### ISSUE TITLE
Pre-fill values

### ISSUE THREAD

**Issue by fragsalat** [ohmyform/ohmyform#100]
#### What's this issue about?
If it is not yet possible it would be helpful if fields could be pre-filled. This way we could send out email surveys and pre-fill email and rating for instance.

#### Environment
All

#### About the Feature
You could extend the default value field and let the user specify which GET parameter should be used to retrieve the default value.

**Comment by wodka** [comment]
can you explain a bit more what the difference to the default value would be? https://demo.ohmyform.com/form/5eeb596e4a9afb0023a70bd4 << has a default value set

**Comment by fragsalat** [comment]
Sure. I want to send out a E-Mail newsletter and let the user answer my survey. The E-Mail would include links from 1 to 10 like `<a href="http://my.survey/form/hash?email=participant@mail.com&rating=1">1</a>`
So the user can fill the rating and email question by just clicking the link in the mail. 

You cann find this feature also on typeform: https://help.typeform.com/hc/en-us/articles/360029664091-Start-your-typeform-in-an-email

PS: Thanks for the fast response :)

**Comment by wodka** [comment]
next version will be able to set a slug on a field, you can use it then to pass the values (with the fallback to use the id of the field)

![image](https://user-images.githubusercontent.com/385731/85117263-e3460000-b21e-11ea-8090-5b5f8bc70bb1.png)

**Comment by wodka** [comment]
?test=12 for the previous screenshot

**Comment by fragsalat** [comment]
Super awesome!  Thank you for the fast support  <3

**Comment by fragsalat** [comment]
Thank you for your help. I pulled the master branches and rebuild the docker container for api the ui. The form edit page shows the Ant popover as you showed it in the screenshot. Unfortunately adding it to the url doesn't prefill the field. For instance `/form/5ef276f5df8f300022121e0a?test=asd`

**Comment by wodka** [comment]
cannot confirm this:

https://demo.ohmyform.com/form/5ef27adb642d220022770ca7?test=fun
https://demo.ohmyform.com/form/5ef27adb642d220022770ca7

this is the "PREFILL_TEST" form in the demo instance

**Comment by fragsalat** [comment]
Ok thank you. Then I will lookup what I did wrong. May I reinstall everything. Is there any other step I have to take for the update except updating api and ui repo and building the docker image again?

**Comment by wodka** [comment]
:/ that should be it - do you see the option to set the slug on the field?

**Comment by fragsalat** [comment]
Yes. That's why I wonder^^
I created a new form + Field with slug test. Using the parameter ?test=asd doesn't fill the field. Regardless if I use default value or not.

![Anmerkung 2020-06-24 000935](https://user-images.githubusercontent.com/1099747/85470224-04a44480-b5af-11ea-8f01-1e46f761da6c.png)

**Comment by wodka** [comment]
ok, this is really strange - I will try tomorrow if I can find a case where this does not work

**Comment by fragsalat** [comment]
And I will try if I can make it work when doing a fresh installation.

**Comment by fragsalat** [comment]
So I did a fresh clone of the root repo. Initiialized the submodules, pulled the master in both and built the docker.
Afterwards I created a new form + field with slug but it does not work for me :*(

**Comment by fragsalat** [comment]
I shortly debugged the part where the field gets it's default and found out the query parameter is not included in the router query object.

See this screenshoot. The expanded query object on the right only contains the ID but not the parameter I passed (qwe=asd)
![Anmerkung 2020-06-25 234243](https://user-images.githubusercontent.com/1099747/85798434-c38e6a80-b73d-11ea-8554-9caac76c4398.png)

**Comment by fragsalat** [comment]
So after some reading it seems like there is a bug in nextjs. It does not actually parse the query params when the page is optimized.
See https://github.com/vercel/next.js/issues/9066 and https://github.com/vercel/next.js/issues/4804
How do you run your application and which nextjs version do  you have?

**Comment by wodka** [comment]
oh, thank you for finding this, so we should start to workaround this with using asPath and manually extracting the parameters then :/

in my installations I use https://github.com/ohmyform/ohmyform/blob/master/examples/docker_for_load_balancing/docker-compose.yml to have next handle also ssr - with nextjs 9.4

**Comment by fragsalat** [comment]
Locally I already added a wrapper to useRouter which parses the query on first render as workaround until its fixed in nextjs. I'll do a pr later this day :)

**Comment by wodka** [comment]
by now also the minimal version includes a running nextjs server
