### ISSUE TITLE
ohmyform isn't runnable.

### ISSUE THREAD

**Issue by piiskop** [ohmyform/ohmyform#101]
#### What's this issue about?

I followed the [installation instructions](https://ohmyform.com/docs/install/) and could bring up the processes, however the address location doesn't respond.

#### Expected behavior

Going to the address location using a web browser, something must be returned, other than _404_.
#### Actual behavior

This site can’t be reached192.168.1.65 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
#### Steps to reproduce

Follow the instructions and see the error! 
/projektid$ git clone https://github.com/ohmyform/ohmyform.git
Cloning into 'ohmyform'...
remote: Enumerating objects: 17992, done.
remote: Total 17992 (delta 0), reused 0 (delta 0), pack-reused 17992
Receiving objects: 100% (17992/17992), 22.60 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (12155/12155), done.
kalmer@test:/projektid$ cd ohmyform/
kalmer@test:/projektid/ohmyform$ git submodule update --init
Submodule 'api' (https://github.com/ohmyform/api) registered for path 'api'
Submodule 'ui' (https://github.com/ohmyform/ui) registered for path 'ui'
Cloning into '/projektid/ohmyform/api'...
Cloning into '/projektid/ohmyform/ui'...
Submodule path 'api': checked out '99fd0b4dc7412e72ca3324810cc1baf6a7790c21'
Submodule path 'ui': checked out '84f23706b5dbea2f77890b8836065892fc2a180b'
I changed the ports in _cocker-compose.yml_ because the ports _5000_, _5050_ and _5051_ were occupied already.
I also had to install _docker-compose_ and get instructions for that elsewhere because these are missing in the former instruction set.
/projektid/ohmyform$ cd ..
kalmer@test:/projektid$ sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   638  100   638    0     0   4089      0 --:--:-- --:--:-- --:--:--  4089
100 11.6M  100 11.6M    0     0   922k      0  0:00:12  0:00:12 --:--:--  940k
kalmer@test:/projektid$ sudo chmod +x /usr/local/bin/docker-compose 
kalmer@test:/projektid$ docker-compose --version
docker-compose version 1.26.2, build eefe0d31
kalmer@test:/projektid$ cd ohmyform/
/projektid/ohmyform$ sudo docker-compose up -d
ohmyform_mail_1 is up-to-date
ohmyform_redis_1 is up-to-date
ohmyform_mongo_1 is up-to-date
ohmyform_mongoexpress_1 is up-to-date
Recreating ohmyform_ohmyform_1 ... done
/projektid/ohmyform$ sudo docker-compose ps
         Name                        Command               State               Ports            
------------------------------------------------------------------------------------------------
ohmyform_mail_1           MailHog                          Up      1025/tcp, 0.0.0.0:5->8025/tcp
ohmyform_mongo_1          docker-entrypoint.sh mongod      Up      27017/tcp                    
ohmyform_mongoexpress_1   tini -- /docker-entrypoint ...   Up      0.0.0.0:6->8081/tcp          
ohmyform_ohmyform_1       docker-entrypoint.sh yarn  ...   Up      3000/tcp, 0.0.0.0:8->5000/tcp
ohmyform_redis_1          docker-entrypoint.sh redis ...   Up      6379/tcp     
#### Environment

_Ubuntu 20.04_, _12.16_

**Comment by Leopere** [comment]
This looks a bit old for what it is, did you resolve this issue?  It does, however, sound like you may have launched multiple copies of this container cluster.

**Comment by piiskop** [comment]
No, I didn't. I'm not very familiar with _docker_ neither. I just followed the instructions.

**Comment by smokedsalmonbagel** [comment]
Is docker running locally or on another machine?  What is the OS docker is running in?  If it is local you should try localhost:3000 or 127.0.0.1:3000.

**Comment by piiskop** [comment]
I'm doing it in another machine with the IP address 192.168.1.65. That machine is running _Ubuntu 18.04_. I did it again:
`almer@test:/projektid/ohmyform$ sudo docker-compose up -d
Starting ohmyform_mail_1  ... done
Starting ohmyform_mongo_1 ... done
Starting ohmyform_redis_1        ... done
Starting ohmyform_mongoexpress_1 ... done
Starting ohmyform_ohmyform_1     ... done
kalmer@test:/projektid/ohmyform$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                           NAMES
dc176220c666        ohmyform_ohmyform   "docker-entrypoint.s…"   4 weeks ago         Up 28 seconds       3000/tcp, 0.0.0.0:8->5000/tcp   ohmyform_ohmyform_1
8dfadba60292        mongo-express       "tini -- /docker-ent…"   4 weeks ago         Up 27 seconds       0.0.0.0:6->8081/tcp             ohmyform_mongoexpress_1
1370e1b10620        mailhog/mailhog     "MailHog"                4 weeks ago         Up 39 seconds       1025/tcp, 0.0.0.0:5->8025/tcp   ohmyform_mail_1
164e8281f657        mongo               "docker-entrypoint.s…"   4 weeks ago         Up 39 seconds       27017/tcp                       ohmyform_mongo_1
c020ee2de4ab        redis               "docker-entrypoint.s…"   4 weeks ago         Up 39 seconds       6379/tcp                        ohmyform_redis_1
d5dae3d2c12a        collabora/code      "/bin/sh -c 'bash st…"   19 months ago       Up 8 days           127.0.0.1:9980->9980/tcp        COLLABORAOFFICE
`
I went to 192.168.1.65:3000 and saw this:
`This site can’t be reached192.168.1.65 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED`

**Comment by wodka** [comment]
could you try with the simple configuration? https://github.com/ohmyform/ohmyform/tree/master/examples/docker_minimal

**Comment by piiskop** [comment]
ERROR: Service 'ohmyform' has a link to service 'mail' which is undefined.

**Comment by wodka** [comment]
can you do a `git pull` before?

**Comment by piiskop** [comment]
kalmer@test:/projektid/ohmyform$ sudo docker-compose up -d
Recreating ohmyform_mail_1 ... 
Recreating ohmyform_mail_1 ... error
Starting ohmyform_redis_1  ... 
WARNING: Host is already in use by another container

Starting ohmyform_mongo_1  ... done
Starting ohmyform_redis_1          ... done
Recreating ohmyform_mongoexpress_1 ... 
Recreating ohmyform_mongoexpress_1 ... error

ERROR: for ohmyform_mongoexpress_1  Cannot start service mongoexpress: driver failed programming external connectivity on endpoint ohmyform_mongoexpress_1 (b934793a4fa764a34e209e591019a1081859bf32d21f38db620fc9aaaf19da54): Error starting userland proxy: listen tcp 0.0.0.0:5051: bind: address already in use

ERROR: for mail  Cannot start service mail: driver failed programming external connectivity on endpoint ohmyform_mail_1 (2e86102e1f0b07545317bffbef0bab28da8169f043255e6110e984dde44b702b): Error starting userland proxy: listen tcp 0.0.0.0:5050: bind: address already in use

ERROR: for mongoexpress  Cannot start service mongoexpress: driver failed programming external connectivity on endpoint ohmyform_mongoexpress_1 (b934793a4fa764a34e209e591019a1081859bf32d21f38db620fc9aaaf19da54): Error starting userland proxy: listen tcp 0.0.0.0:5051: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by wodka** [comment]
this means you are already running one, can you stop all containers and try with the minimal config?

**Comment by piiskop** [comment]
kalmer@test:~$ sudo docker ps
[sudo] password for kalmer: 
Sorry, try again.
[sudo] password for kalmer: 
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                        NAMES
90da29256218        onlyoffice/documentserver   "/bin/sh -c /app/onl…"   8 weeks ago         Up 8 days           80/tcp, 0.0.0.0:5->443/tcp   onlyoffice-document-server
164e8281f657        mongo                       "docker-entrypoint.s…"   2 months ago        Up 3 days           27017/tcp                    ohmyform_mongo_1
c020ee2de4ab        redis                       "docker-entrypoint.s…"   2 months ago        Up 3 days           6379/tcp                     ohmyform_redis_1
d5dae3d2c12a        collabora/code              "/bin/sh -c 'bash st…"   20 months ago       Up 8 days           127.0.0.1:9980->9980/tcp     COLLABORAOFFICE
kalmer@test:~$ sudo docker stop 164e8281f657
164e8281f657
kalmer@test:~$ sudo docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                        NAMES
90da29256218        onlyoffice/documentserver   "/bin/sh -c /app/onl…"   8 weeks ago         Up 8 days           80/tcp, 0.0.0.0:5->443/tcp   onlyoffice-document-server
c020ee2de4ab        redis                       "docker-entrypoint.s…"   2 months ago        Up 3 days           6379/tcp                     ohmyform_redis_1
d5dae3d2c12a        collabora/code              "/bin/sh -c 'bash st…"   20 months ago       Up 8 days           127.0.0.1:9980->9980/tcp     COLLABORAOFFICE
kalmer@test:~$ cd /projektid/ohmyform/
kalmer@test:/projektid/ohmyform$ sudo docker-compose up -d
Removing ohmyform_mail_1
Removing ohmyform_mongoexpress_1
ohmyform_redis_1 is up-to-date
Recreating 1370e1b10620_ohmyform_mail_1 ... 
Recreating 1370e1b10620_ohmyform_mail_1         ... error
Recreating 8dfadba60292_ohmyform_mongoexpress_1 ... 
WARNING: Host is already in use by another container

ERROR: for 1370e1b10620_ohmyform_mail_1  Cannot start service mail: driver failed programming external connectivity on endpoint ohmyform_mail_1 (3f8f9f75df83edbed79e9ea050fa0dfca85b84a75f6dce0c03625638e67be32e): Error starting userland proxy: listen tcp 0.0.0.0:5050: bind: address already in use
Recreating 8dfadba60292_ohmyform_mongoexpress_1 ... error

ERROR: for 8dfadba60292_ohmyform_mongoexpress_1  Cannot start service mongoexpress: driver failed programming external connectivity on endpoint ohmyform_mongoexpress_1 (9993ba26f5b143fa53cc62fcdc065a9579ccf35f74654c6551138005d7d494f9): Error starting userland proxy: listen tcp 0.0.0.0:5051: bind: address already in use

ERROR: for mail  Cannot start service mail: driver failed programming external connectivity on endpoint ohmyform_mail_1 (3f8f9f75df83edbed79e9ea050fa0dfca85b84a75f6dce0c03625638e67be32e): Error starting userland proxy: listen tcp 0.0.0.0:5050: bind: address already in use

ERROR: for mongoexpress  Cannot start service mongoexpress: driver failed programming external connectivity on endpoint ohmyform_mongoexpress_1 (9993ba26f5b143fa53cc62fcdc065a9579ccf35f74654c6551138005d7d494f9): Error starting userland proxy: listen tcp 0.0.0.0:5051: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by wodka** [comment]
this means you have the port for somethin else in use. what you can do is change the ports in the docker-compose file and try again.

**Comment by piiskop** [comment]
ohmyform:
    build: .
    environment:
      CREATE_ADMIN: "TRUE"
      MONGODB_URI: mongodb://mongo/ohmyform
      MAILER_URI: smtp://mail:1025
      PORT: 5000
    links:
      - mongo
      - redis
      - mail
    ports:
      - "8:5000"
kalmer@test:/projektid/ohmyform$ sudo docker-compose up -d
[sudo] password for kalmer: 
Removing ohmyform_mail_1
Removing ohmyform_mongoexpress_1
Recreating 1370e1b10620_ohmyform_mail_1 ... 
ohmyform_redis_1 is up-to-date
Recreating 1370e1b10620_ohmyform_mail_1         ... done
Recreating 8dfadba60292_ohmyform_mongoexpress_1 ... done
Recreating ohmyform_ohmyform_1                  ... done
https://192.168.1.65:8/
This site can’t be reached192.168.1.65 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by Leopere** [comment]
You can’t likely bind to port 8

You should try 80 or something higher.

**Comment by piiskop** [comment]
What do you mean? I there a limit in _ohmyform_ regarding ports? My _apache2_ is running on ports _2_ and _3_ without any problems.

**Comment by Leopere** [comment]
I mean your configuration is asking for port 8 on the host operating system
you need to use a higher port. You should leave the reserved for system
ports the ones in the first a 1024 that are typically reserved for standard
network protocols for the things they’re defined for. Try addressing things
in the higher ranges. It seems that the trend is most people for web
servers use the a 8000 range.

**Comment by piiskop** [comment]
As much as I understand, if the port is free and not reserved then we can use it. Port _8_ is free in my host and it doesn't belong to reserverd ports, so in that matter it's not different from _8000_.

Anyway, I changed the port to _81_ with a no different result.

**Comment by wodka** [comment]
The problem refers to the port being in use because of something. Closing now

**Comment by piiskop** [comment]
I wrote that the port wasn't being in use. I also changed the port to another free port with the same result. Why did you close the issue? This issue isn't solved after almost five months of silence. By closing the issue report, you just send an incorrect signal to users because the issue isn't solved. The problem doesn't refer to the port being in use because of something. The problem refers to _ohmyform_ complaining something about it and that claim seems to be misleading. Two machines, two free ports, nothing works.

**Comment by wodka** [comment]
based on the provided information a port is already in use.

This is the last error Message you posted: all problems correspond to the ports beeing in use

>  ERROR: for 1370e1b10620_ohmyform_mail_1 Cannot start service mail: driver failed programming external connectivity on endpoint ohmyform_mail_1 (3f8f9f75df83edbed79e9ea050fa0dfca85b84a75f6dce0c03625638e67be32e): Error starting userland proxy: listen tcp 0.0.0.0:5050: bind: address already in use
Recreating 8dfadba60292_ohmyform_mongoexpress_1 ... error
> 
> ERROR: for 8dfadba60292_ohmyform_mongoexpress_1 Cannot start service mongoexpress: driver failed programming external connectivity on endpoint ohmyform_mongoexpress_1 (9993ba26f5b143fa53cc62fcdc065a9579ccf35f74654c6551138005d7d494f9): Error starting userland proxy: listen tcp 0.0.0.0:5051: bind: address already in use
> 
> ERROR: for mail Cannot start service mail: driver failed programming external connectivity on endpoint ohmyform_mail_1 (3f8f9f75df83edbed79e9ea050fa0dfca85b84a75f6dce0c03625638e67be32e): Error starting userland proxy: listen tcp 0.0.0.0:5050: bind: address already in use
> 
> ERROR: for mongoexpress Cannot start service mongoexpress: driver failed programming external connectivity on endpoint ohmyform_mongoexpress_1 (9993ba26f5b143fa53cc62fcdc065a9579ccf35f74654c6551138005d7d494f9): Error starting userland proxy: listen tcp 0.0.0.0:5051: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by piiskop** [comment]
Do you mean inside _docker_? I don't know how to check things inside _docker_.

**Comment by wodka** [comment]
The error log is coming from docker, it then depends on you where / how you execute it.

-> https://www.google.com/search?q=docker+bind+address+already+in+use

**Comment by piiskop** [comment]
You're referring to error messages that appeared before I reconfigured the port use. These messages are irrelevant. As you see from a later comment, there was no error message at all, however the app was inaccessible.

I didn't find anything useful in these search results neither. However, I have another try for _ohmyform_. I just want to try it out on my machine and if I have to struggle too much, I classify it as unsuitable and look for an alternative. What I did was:

> kalmer@test:/projektid/ohmyform$ sudo docker-compose up -d
> Starting ohmyform_mongo_1 ... done
> Starting ohmyform_redis_1 ... done
> Starting ohmyform_mail_1  ... done
> Starting ohmyform_mongoexpress_1 ... done
> Starting ohmyform_ohmyform_1     ... done

Everything went up as previously. The configuration is:

>   ohmyform:
> ...
>       MAILER_URI: smtp://mail:1025
>       PORT: 5000
> ...
>     ports:
>       - "81:5000"
>   mail:
>     image: mailhog/mailhog
>     ports:
>       - "9:8025"
>   mongoexpress:
> ...
>     ports:
>       - "10:8081"
> 

At the port _10_, there's _mongoexpress_ running. The ports _9_ and _81_ give no web interface. However the ports are connected to the just started _docker_ container. They were unoccupied before:

> kalmer@test:/projektid/ohmyform$ sudo netstat -plunt |grep :81
> tcp6       0      0 :::8126                 :::*                    LISTEN      2137/metrics        
> tcp6       0      0 :::81                   :::*                    LISTEN      337842/docker-proxy 
> ...
> kalmer@test:/projektid/ohmyform$ sudo netstat -plunt |grep :9
> tcp        0      0 127.0.0.1:9980          0.0.0.0:*               LISTEN      3405/docker-proxy   
> tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      1157/dovecot        
> tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      1163/named          
> tcp6       0      0 :::993                  :::*                    LISTEN      1157/dovecot        
> tcp6       0      0 :::9                    :::*                    LISTEN      337350/docker-proxy 
> ...
> kalmer@test:/projektid/ohmyform$ sudo netstat -plunt |grep :10
> tcp        0      0 127.0.0.1:10023         0.0.0.0:*               LISTEN      1040/postgrey --pid 
> tcp6       0      0 :::1024                 :::*                    LISTEN      819/node            
> tcp6       0      0 :::10                   :::*                    LISTEN      337822/docker-proxy 
> 

Here are all the running containers:

> kalmer@test:/projektid/ohmyform$ sudo docker ps
> CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                            NAMES
> 64c5e4102307        ohmyform_ohmyform           "docker-entrypoint.s…"   4 months ago        Up 10 minutes       3000/tcp, 0.0.0.0:81->5000/tcp   ohmyform_ohmyform_1
> 9ba7643b16f6        mongo-express               "tini -- /docker-ent…"   4 months ago        Up 10 minutes       0.0.0.0:10->8081/tcp             ohmyform_mongoexpress_1
> 8db431c30e94        mailhog/mailhog             "MailHog"                4 months ago        Up 10 minutes       1025/tcp, 0.0.0.0:9->8025/tcp    ohmyform_mail_1
> 90da29256218        onlyoffice/documentserver   "/bin/sh -c /app/onl…"   6 months ago        Up 43 hours         80/tcp, 0.0.0.0:5->443/tcp       onlyoffice-document-server
> 164e8281f657        mongo                       "docker-entrypoint.s…"   7 months ago        Up 10 minutes       27017/tcp                        ohmyform_mongo_1
> c020ee2de4ab        redis                       "docker-entrypoint.s…"   7 months ago        Up 10 minutes       6379/tcp                         ohmyform_redis_1
> d5dae3d2c12a        collabora/code              "/bin/sh -c 'bash st…"   2 years ago         Up 43 hours         127.0.0.1:9980->9980/tcp         COLLABORAOFFICE

So if a port that has to be occupied is occupied already then it must be because _ohmyform_ had occupied it at first place.

**Comment by wodka** [comment]
So based on your new run it is working - when no ports are used it comes up correctly.

**Comment by wodka** [comment]
just saw that you are using a build compose file - there is no support running those. you can use the prebuilt images

**Comment by piiskop** [comment]
> So based on your new run it is working - when no ports are used it comes up correctly.

I was running in September already. It isn't working. I can't access the address and port combination where the software should be accessible.

**Comment by piiskop** [comment]
> just saw that you are using a build compose file - there is no support running those. you can use the prebuilt images

Would you elaborate what you mean? Are you sure you've read the whole thread? Because somebody suggested to use the minimal configuration. I'm not sure where I get a prebuilt image from and how I configure it for different ports.

**Comment by wodka** [comment]
yes, this was me - and it seems like you are still trying to do something different: https://github.com/ohmyform/ohmyform/tree/master/examples/docker_minimal 

As the images are working I suggest you use them and find out what is running on your system already or if you want to rebuild the platform read into the docker files and package.json files
