### ISSUE TITLE
Make Mail configuration more convenient

### ISSUE THREAD

**Issue by chronikum** [ohmyform/ohmyform#103]
#### What's this issue about?
Make it easier to configure a mail server
#### About the Feature
**First:** Really liking your project and planning to actively contribute to it!.
But I found it a little hard to get started and configure the values you need to set.
I think it would be great if you could specify an smtp host, an smtp username and password directly in the docker-compose. Doing it with `smtp://` is actually a bit hard and inconvenient.

If there is something I missed with the configuration, sorry! I could not find any documentation on this other than the `MAILER_URI.`

**Comment by Leopere** [comment]
I think the one thing that isn't obvious is how to enable SMTP encryption options. https://github.com/ohmyform/ohmyform/blob/master/docker-compose.yml#L19 looks fairly straight forward where `smtp://mail:1025` **mail**=the container name of the **mailhog container** address and `:1025` is the port that **mailhog** operates on.  The docker-compose.yml is really just a kick the tires boilerplate for download and go.  It definitely leaves a fair bit to be desired but on our last major volley of available time for commitment for dev'ing this project we made a huge push for stable 1.0 status.  Next is a huge documentation sprint and some UI/UX polish.

**Comment by Leopere** [comment]
Perhaps tagging in @wodka on this one for documentation would be ideal.

**Comment by wodka** [comment]
by now it is documented in https://github.com/ohmyform/api/blob/master/doc/environment.md
