### ISSUE TITLE
I want to do this, is ohmyform the right tool?

### ISSUE THREAD

**Issue by mikkeschiren** [ohmyform/ohmyform#104]
Just start to looking into Ohmyform, and I do like it. 

I have an use case that I would like to use forms in another application, I can see that there an API - you I use that for it? Or do I need to embed the forms? And what are the best practice for doing so? Like using URL for the public address in a iframe?

**Comment by Leopere** [comment]
Typically the best method for this type of Q&A is in the Discord but what I will say is that you're absolutely encouraged to reach into the API directly with whatever you like.  

We're not super sticklers for the AGPLv3 on here but do please consider contributing back any derivatives you create.  

You can embed the UI but its absolutely encouraged to write alternative UI's for it.

**Comment by mikkeschiren** [comment]
Ok, thanks - just for info I tried to join Discord before posting - but I got the message that the invitation was invalid.

**Comment by rawzone** [comment]
> Ok, thanks - just for info I tried to join Discord before posting - but I got the message that the invitation was invalid.

Jup invite links still dead... @mikkeschiren did you find another project or did you go ahead with ohmyform?
