### ISSUE TITLE
How to run ohmyform if  i have already succesfully install via docker

### ISSUE THREAD

**Issue by mbahsaptojr** [ohmyform/ohmyform#105]
#### What's this issue about?

I have already install ohmyform on my docker

ohmyform_mail_1           MailHog                          Up      1025/tcp, 0.0.0.0:5050->8025/tcp
ohmyform_mongo_1          docker-entrypoint.sh mongod      Up      27017/tcp                       
ohmyform_mongoexpress_1   tini -- /docker-entrypoint ...   Up      0.0.0.0:5051->8081/tcp          
ohmyform_ohmyform_1       docker-entrypoint.sh yarn  ...   Up      3000/tcp, 0.0.0.0:5000->5000/tcp
ohmyform_redis_1          docker-entrypoint.sh redis ...   Up      6379/tcp      

but how I could check if ohmyform running properly?

**Comment by wodka** [comment]
perhaps it is easier for you to simpliy run the minimal configuration: 

https://github.com/ohmyform/ohmyform/tree/master/examples/docker_minimal

in general you can use to tools provided by docker to check for running services
