### ISSUE TITLE
Unable to go beyond landing page localhost:5000

### ISSUE THREAD

**Issue by AndreLesa** [ohmyform/ohmyform#106]
#### What's this issue about?
Unable to go beyond landing screen.

#### Expected behavior
After installation with docker-compose up - I should be able to go to localhost:5000 then admin.

#### Actual behavior
Clicking on admin simply reloads the landing page.

#### Steps to reproduce
Install with docker compose up, open localhost:5000

#### Environment
Docker compose

**Comment by philippremy** [comment]
I suggest logging on via the root user. In case you created a new user, this one does not have enough permissions to reach the administration page. Standard admin account:
username: root
password: root

Log on with the root user and you can reach administration page!
