### ISSUE TITLE
Anonymous submissions for human subjects research

### ISSUE THREAD

**Issue by smokedsalmonbagel** [ohmyform/ohmyform#108]
#### What's this issue about?

Feature request for very common use case in research - anonymous surveys.

#### About the Feature

For human subjects research (IRB reviewed, etc) survey applications need to provide a high level of anonymity.  It looks like OhMyForm seems to store /collect some user data at least internally.  It would be great to have a configuration option to make a survey fully anonymous.  If this is already a feature it would be great to know how it could be enabled.  If not, adding this feature  it could make OhMyForm very attractive to the research community. 

Maybe a good starting point would be identifying the places where OMF records personal data (IP,country,state,User agent etc.).

**Comment by wodka** [comment]
as of now we do not have this.

What needs to be done here:
* add an option to the form configuration (api + ui)
* then simply not store it in the form submission (api)


can you provide a PR for this?

**Comment by wodka** [comment]
![image](https://user-images.githubusercontent.com/385731/147907199-03e7a7e1-2f2c-42f3-b11d-85075ea8eabd.png)

next release will have this - IP's are then masked by default and the user is only stored if anonymous is not active
