### ISSUE TITLE
New form not being created

### ISSUE THREAD

**Issue by mazharalibaig** [ohmyform/ohmyform#109]
#### What's this issue about?

I have been able to open the admin settings using the root credentials, however, on creating a form and saving it does not show in my forms i.e created forms are not persisting.

#### Expected behavior

Form should be created
#### Actual behavior

Form is being saved (according to notification) but on going back it does not show the new form
#### Steps to reproduce

Just follow the normal routine of creating a form
#### About the Feature

I would like to see what I am doing wrong or if this is a bug

**Comment by paulb-opusvl** [comment]
I too am able to replicate this issue from a fresh docker install.

**Comment by wodka** [comment]
I was not yet able to reproduce it.

if you start the basic system by: https://github.com/ohmyform/ohmyform/tree/master/examples/docker_minimal does this error occure?

what configuration are you using?
