### ISSUE TITLE
Mobile UI, buttons off screen 

### ISSUE THREAD

**Issue by Tam2** [ohmyform/ohmyform#114]
## What's this issue about?
Trying the demo out on mobile, the buttons are off the bottom of the screen 
E.g.
https://demo.ohmyform.com/form/5f4f07af60c08b0022c7add9

#### Expected behavior
Should be able to see buttons on mobile 

#### Actual behavior
The buttons are off the screen, see screenshot 

![Screenshot_20200922-222951](https://user-images.githubusercontent.com/1256087/93939990-a01a9200-fd23-11ea-875b-4a11d890d024.jpg)

#### Steps to reproduce
Visit on a mobile device 
https://demo.ohmyform.com/form/5f4f07af60c08b0022c7add9
#### Environment
Chrome on Android, oneplus 7 Pro

**Comment by wodka** [comment]
Thanks for reporting, I can reproduce it on other phones as well :/

**Comment by Tam2** [comment]
Another observation, the actual question seems to be too far down on the page, shouldnt it be centered vertically?

**Comment by SinoBoeckmann** [comment]
I found a "workarround" or more like a hack for now. By setting a max-height to the page and the form-container.


```
#ui/components/form/page.module.scss
.main {
  display: flex;
  flex-direction: column;

  .content {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    overflow: auto;
    padding: 16px;

    max-height: 78vh;

    @media (max-width: 600px) {
      display: block;
    }
  }
}
```

```
#ui/components/form/field.tsx
<div
  style={{
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: 32,
    justifyContent: 'flex-end',
    maxHeight: '78vh',
  }}
>
```

But this is just a current-hack-solution. There is for sure, a better solution, to do this. But this one is currently fine for me.
