### ISSUE TITLE
CLI installation without a docker

### ISSUE THREAD

**Issue by mihha** [ohmyform/ohmyform#116]
Hi,

this is not an issue as such but would like to ask (didn't find the answer anywhere) is it possible to get instructions how to build and execute the app using CLI only without a docker?

For various reasons, I really don't like or want to use Docker.

Did someone manage to build and run this app without a Docker? Any instruction or point into the right direction would be helpful

Thank you all in advance!

Regards,
Igor

**Comment by wodka** [comment]
Hi @mihha 

all information needed for this is within the Dockerfiles - they are by definition nothing more than a basic Linux that gets certain commands executed to be runnable.

in short:

1) Checkout API and install dependencies
2) Checkout UI and install dependencies
3) start both and connect through some Reverse Proxy like NginX or traefik.
