### ISSUE TITLE
Conditional/dependencies support?

### ISSUE THREAD

**Issue by Lilja** [ohmyform/ohmyform#117]
In the sense of if the user picks a value, a different set of form options appears for a more dynamic form.

Does OhMyForm support this kind of feature?

**Comment by NeoTheThird** [comment]
It does not, as far as i can see. I would very much like to see this!

**Comment by Adrian-Samuel** [comment]
This would be amazing, I reckon would take a fair bit of work since the UI state ould need to match

**Comment by wodka** [comment]
it is now partially there - backend is prepared for conditions / formula based logic. it should land in the 1.0.0 release for the ui as well.

**Comment by wodka** [comment]
![image](https://user-images.githubusercontent.com/385731/118375318-4ec85700-b5c1-11eb-8762-898bb91d5801.png)

dynamic conditions are on their way :)

**Comment by wodka** [comment]
logic actions are now released in 1.0.0
