### ISSUE TITLE
Error on signup

### ISSUE THREAD

**Issue by wodka** [ohmyform/ohmyform#12]
#### What's this issue about?

App crashes when a user tries to sign up

#### Expected behavior

user should be signed up without crash

#### Actual behavior

app crashes

#### Steps to reproduce

enable signup and signup a new user

#### Environment

---

**Comment by Leopere** [comment]
Emails should be possible but not required however the only mail that gets SENT is the verification email until the user confirms their email.

**Comment by assembledadam** [comment]
I get this too, can't even sign-up to demo the app locally... I either get a random error message or the thing just crashes.

**Comment by Leopere** [comment]
I should really disable the sign-up function on the demo.

**Comment by victorbordo** [comment]
I'm also experiencing this issue locally. The error message is blank `{"message":""}`

**Comment by Leopere** [comment]
We’re getting there I swear. We just want to get the rewrite right.

**Comment by victorbordo** [comment]
Thanks! Really looking forward to trying it out. If there's a quick way to disable auth lmk and I'll rebuild locally.

**Comment by Leopere** [comment]
I vaguely imagine it's been mentioned somewhere around this thread but 

# Current state of Authentication
Not quite there yet, however you can log into the administration account with username and password `root root` ultimately this should be modifiable in the environment variables as well so you don't need default credentials but I can't confirm this.

**Comment by almereyda** [comment]
Thanks for the root hint, which should also find its way into #42.

The signup errors derieve from an unconfigured MDA:

```
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] Starting session
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] [PROTO: INVALID] Started session, switching to ESTABLISH state
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] Sent 35 bytes: '220 mailhog.example ESMTP MailHog\r\n'
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] Received 18 bytes: 'EHLO [127.0.0.1]\r\n'
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] [PROTO: ESTABLISH] Processing line: EHLO [127.0.0.1]
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] [PROTO: ESTABLISH] In state 1, got command 'EHLO', args '[127.0.0.1]'
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] [PROTO: ESTABLISH] In ESTABLISH state
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] [PROTO: ESTABLISH] Got EHLO command, switching to MAIL state
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] Sent 23 bytes: '250-Hello [127.0.0.1]\r\n'
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] Sent 16 bytes: '250-PIPELINING\r\n'
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] Sent 16 bytes: '250 AUTH PLAIN\r\n'
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] Connection closed by remote host
mail_1          | 2019/10/24 15:38:50 [SMTP 172.19.0.6:41050] Session ended
ohmyform_1      | {"message":"\u001b[0mPOST /auth/signup \u001b[33m400 \u001b[0m109.759 ms - 14\u001b[0m\n","level":"info"}
```

**Comment by MartinDelille** [comment]
I also have the issue.

I don't have experience on it but instead of reinventing the wheel, what would you think about implementing authentification via service like https://auth0.com/? It's free for a decent amount of user.

**Comment by Leopere** [comment]
I think my preference lies in using pure FOSS tools like SQRL or whatever is in the JS framework that @wodka is using rather than some proprietary third party that collects metadata.  As for reinventing the wheel, we're using things like bcrypt and whatnot already in the rewrite.

**Comment by wodka** [comment]
the new api no longer crashes on reregistering with an invalid email server - the log contains now a note in case an email could not be sent
