### ISSUE TITLE
Russian language is no available

### ISSUE THREAD

**Issue by azhinu** [ohmyform/ohmyform#121]
#### What's this issue about?

If choose russian language while creating form I'm getting an error.
```
create-7c637b9bf8f55a93bfec.js:1 failed to save Error: GraphQL error: Form validation failed: language: `ru` is not a valid enum value for path `language`.
```
Message from chrome console.

#### Steps to reproduce

Add new form with 'Language' set to 'русский язык'
#### Environment

Self-hosted docker-compose minimal.

**Comment by wodka** [comment]
added in 0.9.9
