### ISSUE TITLE
Admin login rejected

### ISSUE THREAD

**Issue by deflepp** [ohmyform/ohmyform#122]
#### What's this issue about?
I Installed ohmyform via caprover twice now. The installation and deployement succeeds, but then I can't log in with the credentials of the set up process (login/password incorrect). I also can't add users (credentials already in use) eventhough  nothing is th same.  I'm on caprover 1.8.2.

#### Expected behavior
I'm expecting to be able to log in with the admin credentials.

#### Actual behavior
I can't. I even tried to set the env. variables, no success.

#### Steps to reproduce
Installing ohmyforms via caprover one-click.

**Comment by ruiisidro** [comment]
I've got this issue too. Any news?

**Comment by Lastofthefirst** [comment]
Same issue here, any updates?

Recover password leads to Work in Progress page, and create account failed with the error "data already in use"

**Comment by omogolo** [comment]
Same issue: "username / password are invalid" or "data already in user"
Admin, Login, Create account fails to login.

**Comment by FredericoGauz** [comment]
It seems that we are lacking a better (user friendly) error from authentication. I was getting these errors when the problem was actually on the API itself. Please check your console to see if there is no issue with the client - api connection.

**Comment by githubber** [comment]
I just installed OhMyForm too on Caprover, had the same error, and a Google search led me here. After perusing a bit and thinking about it, I took a hint from @FredericoGauz and took a look at my captain.example.com/#/apps/details/form-api dashboard. There, under App Configs, the first table reads CREATE_ADMIN, and is set to true. So, I changed it to false, and now I can login. Yay!
![caprover-ohmyform](https://user-images.githubusercontent.com/3861/113184613-b155d580-9255-11eb-8593-5487d0a7058c.jpg)

**Comment by wodka** [comment]
there is now more documentation on environment variables (https://github.com/ohmyform/api/blob/master/doc/environment.md)

and on the homepage it now shows a message in case there is no connection to the backend api

**Comment by githubber** [comment]
Re-open this. Using Caprover, latest. With OhMyForms. Admin login, regular login, both saying `username / password are invalid`. Still a shame. I double checked the various env variables and its all as it should be. 
There is an extra notice though: `2022-02-24T10:47:37.132751429Z {"level":50,"time":1645699657132,"pid":34,"hostname":"799e63f45d90","context":"MongooseModule","trace":"","msg":"Unable to connect to the database. Retrying (6)..."}`

**Comment by 9j7axvsLuF** [comment]
I have the same issue - any update?

**Comment by wodka** [comment]
-> caprover uses an old image... https://github.com/ohmyform/ohmyform/issues/136

**Comment by 9j7axvsLuF** [comment]
I used the new image and still have the same issue. First of all, the app runs on port 4000 instead of 5000. When I change the `Container HTTP Port` to 5000 on Caprover I load the landing page, but I get an error at the bottom:

`There is an error with your API connection: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

And when I try to log in, I get the error `username / password are invalid`.

**Comment by osulluke** [comment]
I am also having this issue. Changing environment variables doesn't fix it for me either.

**Comment by heyakyra** [comment]
In the browser, I see a request to `/graphql` which responds with a 404, so there must be a bug in the default configuration
