### ISSUE TITLE
Dropdown can't change input

### ISSUE THREAD

**Issue by phil8900** [ohmyform/ohmyform#123]
#### What's this issue about?
I am running OhMyForm after installing it via docker pull using the minimal configuration. I set up a test form and added a text field (which is working fine) and a dropdown which is causing problems.
When I click on the dropdown when there is no value selected it works and I can select a value. If I want to change the value and click on the dropdown again, nothing happens and I cannot change the value.

#### Expected behavior
A mouse click should open the dropdown selection and allow the user to change previous input.

#### Actual behavior
A mouse click doesn't open the dropdown and the value can't be changed. Sometimes the dropdown opens when I use the mouse wheel button or the right mouse button, but I can't really reproduce that.

#### Steps to reproduce
Create a simple form with a dropdown and select a value. Then try to change the selected value using the left mouse button.

#### Environment
Client:
Windows 10 Pro 20H2
Firefox 84.0.1

Server:
Ubuntu 18.04
nginx 1.14

**Comment by wodka** [comment]
I cannot reproduce this in the latest version
