### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by adjwills** [ohmyform/ohmyform#126]
#### What's this issue about?
Demo at https://demo.ohmyform.com/login isn't working for me

#### Expected behavior
Wanted to see the demo (this looks like a great project!)

#### Actual behavior
![Screenshot 2021-01-28 at 17 02 15](https://user-images.githubusercontent.com/19974436/106172336-9fd74b00-618a-11eb-89c2-ef0b3baf01ef.png)

#### Steps to reproduce
Try https://demo.ohmyform.com/login

**Comment by wodka** [comment]
will update the link soon to heroku: https://omf-demo.herokuapp.com/

thx for reporting!

**Comment by timh777** [comment]
Hello, This looks great, and really want to take a look at it but the demo site is not loading the form builder for me

https://www.screencast.com/t/N3prSSsAJv

thanks
