### ISSUE TITLE
Heroku 1-click - "mongolab" does not exist

### ISSUE THREAD

**Issue by adjwills** [ohmyform/ohmyform#127]
#### What's this issue about?
Tried Heroku 1-click deploy https://heroku.com/deploy?template=https://github.com/ohmyform/ohmyform/tree/master... am guessing this might be the issue? https://devcenter.heroku.com/articles/mongolab

Since "Ditch MongoDB for a drop in replacement with better licensing." is on your roadmap, just a quick +1 for postgres

#### Expected behavior
Deploy to Heroku

#### Actual behavior
![Screenshot 2021-01-28 at 17 08 16](https://user-images.githubusercontent.com/19974436/106173314-b336e600-618b-11eb-804a-d2217f424178.png)

#### Steps to reproduce
Try https://heroku.com/deploy?template=https://github.com/ohmyform/ohmyform/tree/master

**Comment by wodka** [comment]
:/ we are working on replacing mongo with postgres anyway. We should remove the deploy with heroku in the mean time

**Comment by adjwills** [comment]
Ah ok, good to know. Great to hear your migrating this to postgres, +1

I was thinking of playing around with the docker image locally, based on your local development notes here https://ohmyform.com/docs/install/ do you think it's worth waiting until the postgres migration is done? I was just keen to play around with it for now... would definitely prefer to use the postgres update when it's ready to go in future

**Comment by wodka** [comment]
https://github.com/ohmyform/ohmyform/tree/master/example << you can pick this as a simple local version. It will take a while to have the postgres version ready.

**Comment by adjwills** [comment]
I managed to build a local version and play around with it. Looks good! Will keep a look out for the postgres version in future for sure. Thanks.

**Comment by nirmalhk7** [comment]
Is it not possible to have a temporary fix for this?

**Comment by wodka** [comment]
the heroku deploy is now fixed - and uses postgres as a backend.
