### ISSUE TITLE
Keep being redirected to index

### ISSUE THREAD

**Issue by FredericoGauz** [ohmyform/ohmyform#128]
#### What's this issue about?
After successful authentication, I keep getting redirected to index (from admin)

#### Expected behavior
See the admin of OhMyForms

#### Actual behavior
Get redirected to index "With just Forms image"

#### Environment
Docker Composer

#### Obs:

I saw that this project run on a tech stack I am familiar, if someone let me know what might be the cause I will be happy to help solving it.

**Comment by wodka** [comment]
I guess the user is not an admin then. You can change that either in the DB or use the default root/root

**Comment by wodka** [comment]
there have been a few improvements that are now coming to 1.0.0 - probably those will fix the issue
