### ISSUE TITLE
Assistance in packaging for Cloudron.io

### ISSUE THREAD

**Issue by vRobM** [ohmyform/ohmyform#130]
As part of the [Cloudron community](https://forum.cloudron.io) we're super excited to have OMF available on our beloved platform.

Would any of the developers here be interested in kindly helping us package the app?

We have a thread going here with a gaggle of users itching to use it: https://forum.cloudron.io/post/7413

**Comment by wodka** [comment]
sounds nice, we are approaching 1.0 that will shift a few things internally (like switch from mongodb to postgres)

@vRobM what kind of help would you need?

**Comment by vRobM** [comment]
Wonderful. Good, we have Postgres.

The packaging involves understanding the app internals and organizing the files into a specifically configured container according to this guide.

https://docs.cloudron.io/custom-apps/tutorial/

**Comment by wodka** [comment]
ok, just from the way I understand it - this is no hosting service but a tool that "simplifies" the deployment to a server?

can you provide a yaml file for the base configuration? As a basis for the required configuration you can also take a look at the app.json file for heroku: https://github.com/ohmyform/ohmyform/blob/master/app.json or the sample docker compose files https://github.com/ohmyform/ohmyform/tree/master/examples

**Comment by vRobM** [comment]
Cloudron manages servers easily making it a delight to self-host and has a "few click" install for 50+ apps.

We don't use yaml files, hence the request to get familiar with the packaging requirements. Please review the tutorial above as it contains critical information like the brilliant read-only filesystem.

**Comment by wodka** [comment]
Sry, I meant the cloudron manifest json file.

you probably have a system running where you can test it :)

**Comment by vRobM** [comment]
There are examples already provided at the tutorial link above.

**Comment by wodka** [comment]
When they are working please submit a PR :)

**Comment by Hillside502** [comment]
> ...has a "few click" install for 50+ apps.
> 
110+ apps
