### ISSUE TITLE
failed to start submission Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by fuerst** [ohmyform/ohmyform#137]
#### What's this issue about?

Anonymous Form submission does not show up at admin panel.

#### Expected behavior

Anonymous Form submissions are expected to be shown at the "Submissions" section of a form.

#### Actual behavior

As anonymous user: At the form submission UI nothing unexpected happens.
When loading a form the browser console though is logging: `failed to start submission Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed`. See attached screenshot for details.

Form submission for logged in users works as expected.

#### Steps to reproduce

1. Start a OhMyForm instance using https://github.com/ohmyform/ohmyform/blob/master/examples/docker_minimal/docker-compose.yml
2. Create a form containing 1 Text field and 1 Date field, activate "Is live".
3. Fill out the form using a second and private browser window

#### Environment

* Browser: Ungoogled Chromium Version 91.0.4472.77
* macOS 11.4
* OhMyForm 1.0.0-alpha
<img width="949" alt="OhMyForm - SQLITE_CONSTRAINT FOREIGN KEY" src="https://user-images.githubusercontent.com/582648/120799691-5e431c00-c53f-11eb-982a-5e7e7f0dfe71.png">

**Comment by wodka** [comment]
fixed in master
