### ISSUE TITLE
[Feature] Multiple choice field / Checkboxes

### ISSUE THREAD

**Issue by Dynnammo** [ohmyform/ohmyform#138]
#### What's this issue about?
As a user, when creating a form, I would like to create questions with multiple possible answers.
E.g if the question is « what language are you talking ? », I can check _english_, _french_ and _spanish_, or nothing, or just _english_ and validate that answer.

#### About the Feature
When creating a form, I would add a 12th possibility named "Checkbox", on which people can add answers the as for "Radio" field. When filling the form, we can check boxes with keystrokes.

**Comment by wodka** [comment]
![image](https://user-images.githubusercontent.com/385731/147909408-a507aed2-2a99-442b-894a-d15d6c0f3cb0.png)

there is now a new checkbox type in master, will be released in 1.0

**Comment by Dynnammo** [comment]
Just wow ! Warm thanks @wodka. I'll forward to it !
