### ISSUE TITLE
newly created forms not visible

### ISSUE THREAD

**Issue by andrewchenshx** [ohmyform/ohmyform#139]
#### What's this issue about?
after creating a form and saving it, it does not show in my forms.

#### Expected behavior
newly created form DOES show in my forms.

#### Actual behavior
newly created form does NOT show in my forms.

#### Steps to reproduce
0. install the app by following the minimal conf as https://github.com/ohmyform/ohmyform/blob/master/examples/docker_minimal/docker-compose.yml
1. navigate home/forms, press "new form", fill in "title" & "language", then "save".
2. navigate home/forms, the list is empty.

docker Log:
{"level":50,"time":1628786482732,"pid":70,"hostname":"ohmyform-ohmyform1","msg":"failed to add installation metrics"}

not sure is it related.

**Comment by Jazys** [comment]
I confirm the bug, even if you add element, on form and save it.
After some minutes and refresh manually page, forms appear.

So backend is Ok but error in frontend ?

**Comment by wodka** [comment]
fixed in master
