### ISSUE TITLE
request for Directadmin (simpler user here)

### ISSUE THREAD

**Issue by mikulabc** [ohmyform/ohmyform#141]
I found ohmyform online but i am not one of those advanced devs, i simply use Directadmin on a VPS and i was wondering if there is any way you could add a guide on how to install it as simply as most wordpress installations go?

**Comment by wodka** [comment]
you would need a host with nodejs running or ideally with container support.

**Comment by wodka** [comment]
then it would be as simple as picking one compose and running it: https://github.com/ohmyform/ohmyform/tree/master/examples
