### ISSUE TITLE
Feature request: Anonymous submissions

### ISSUE THREAD

**Issue by OoLunar** [ohmyform/ohmyform#142]
#### What's this issue about?
Feature request: Anonymous submissions 

#### About the Feature
The main reason why I'm using OhMyForms over Google Forms is because we can use our custom emails with it. However, one missing feature that I find missing from OMF is anonymous form submissions. Way to many times, individuals will want to take a vote, only to realize that their friends didn't choose the option that they expected them too. Anonymous submissions can also lead to unbiased judging and allows for some to see the numbers over the people completing the form.

**Comment by wodka** [comment]
will be part of version 1.0
