### ISSUE TITLE
Form-field slider cannot be saved

### ISSUE THREAD

**Issue by Yasamato** [ohmyform/ohmyform#144]
#### What's this issue about?
Creating a form field of type slider results in the whole form failing to save returning a `400 Bad Request` error

#### Expected behavior
The form changes should be saved

#### Actual behavior
Request returns a `400 Bad Request` http header with the message:

```json
{
    "errors": [
        {
            "message": "Variable \"$form\" got invalid value 100 at \"form.fields[0].options[0].value\"; String cannot represent a non string value: 100",
            "locations": [
                {
                    "line": 1,
                    "column": 17
                }
            ],
            "extensions": {
                "code": "BAD_USER_INPUT"
            }
        },
        {
            "message": "Variable \"$form\" got invalid value 1 at \"form.fields[0].options[1].value\"; String cannot represent a non string value: 1",
            "locations": [
                {
                    "line": 1,
                    "column": 17
                }
            ],
            "extensions": {
                "code": "BAD_USER_INPUT"
            }
        },
        {
            "message": "Variable \"$form\" got invalid value 100 at \"form.fields[0].options[2].value\"; String cannot represent a non string value: 100",
            "locations": [
                {
                    "line": 1,
                    "column": 17
                }
            ],
            "extensions": {
                "code": "BAD_USER_INPUT"
            }
        },
        {
            "message": "Variable \"$form\" got invalid value 1 at \"form.fields[0].options[3].value\"; String cannot represent a non string value: 1",
            "locations": [
                {
                    "line": 1,
                    "column": 17
                }
            ],
            "extensions": {
                "code": "BAD_USER_INPUT"
            }
        }
    ]
}
```

#### Steps to reproduce
1. `mkdir ohmyform` and `cd ohmyform`
2. `wget https://raw.githubusercontent.com/ohmyform/ohmyform/master/examples/docker_nginx/docker-compose.yml`
3. `wget https://raw.githubusercontent.com/ohmyform/ohmyform/master/examples/docker_nginx/default.conf`
4. `docker-compose up -d`
5. Go to `http://localhost:8080` and login using the defaults for the admin credentials in the [docker-compose.yml](https://github.com/ohmyform/ohmyform/blob/master/examples/docker_nginx/docker-compose.yml)
6. Crete a new form
7. Add a new form field of type `slider` and fill in a title
8. Click save

#### Environment
```bash
docker --version
Docker version 20.10.8, build 3967b7d

docker-compose --version
Docker Compose version v2.0.0-rc.3
```

My best guess would be that `parseInt` is just missing in the ui before it get's sent to the api.

**Comment by wodka** [comment]
should be fixed in current master - will be in 1.0
