### ISSUE TITLE
User Management in Backend

### ISSUE THREAD

**Issue by wodka** [ohmyform/ohmyform#15]
#### What's this issue about?

Right now users can register but there is no way to manage them

#### Expected behavior

add at least a minimal user management in the backend

**Comment by Leopere** [comment]
So far "can register" is also not a possibility according to #12

**Comment by loleg** [comment]
In the meantime, users can be "managed" by editing the data in the MongoDB users collection. Not user friendly. Dangerous. +1 for some kind of an interface for this - at least to even just see a list of users in the system as a start.

**Comment by wodka** [comment]
new backend can manage users

![Screenshot 2020-06-01 at 21 54 37](https://user-images.githubusercontent.com/385731/83746487-6ed86200-a65f-11ea-8bb0-d2560837f690.png)
