### ISSUE TITLE
Slider and form removal

### ISSUE THREAD

**Issue by foxhoundv** [ohmyform/ohmyform#150]
#### What's this issue about?
Adding a slider to a form and deleting a form.

#### Expected behavior
I wanted to add a slider to a form to see what it does. I also wanted to see what happens when deleting a form.

#### Actual behavior
When adding items to the form, I try to add a slider and it gives me a blank page that says, "Application error: a client-side exception has occurred (see the browser console for more information)." Also, when I created a test form with only a few items, I tried to delete it and after confirming that I want to delete is says, "Could not delete form".

#### Steps to reproduce
When adding items to a form, try adding a slider. After creating a test form, try to delete it.

#### Environment
Ubuntu 20.04.03 LTS, I am using Docker Version 20.10.10, API 1.41

**Comment by fdeus** [comment]
I confirm to have the same issues.
Running on Docker Desktop 4.4.2, Docker Engine 20.10.12, Docker Compose 1.29.2

OhMyForm version 1.0.0

**Comment by wodka** [comment]
Problem is coming from context handling `const context = React.useContext(FormItemContext)`

Stack trace:
```
react_devtools_backend.js:4061 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.to (react-dom.production.min.js:156:258)
    at Object.t.useContext (react.production.min.js:22:273)
    at children (slider.type.tsx:14:27)
    at FormItem.js:325:19
    at n.i.getOnlyChild (Field.js:419:67)
    at n.value (Field.js:595:37)
    at $o (react-dom.production.min.js:187:188)
    at Bo (react-dom.production.min.js:186:173)
    at Hu (react-dom.production.min.js:269:427)
    at Pi (react-dom.production.min.js:250:347)
```
