### ISSUE TITLE
submissions / empty form are persisted

### ISSUE THREAD

**Issue by oopen** [ohmyform/ohmyform#153]
#### What's this issue about?
Empty / not validated forms are persisted, even with required question

#### Expected behavior
Not persist empty or not full answered forms

#### Actual behavior

No persist it,
or count not full leaved form

#### Steps to reproduce
Create form, go to it, leave page.
Go to submissions, form emty form is persisted

#### Environment
Docker compose minimal

![Screenshot 2022-02-05 at 11-11-32 OhMyForm](https://user-images.githubusercontent.com/7348132/152638392-327a3fb5-2f24-4e59-a2d1-027af4509023.png)

**Comment by wodka** [comment]
fixed in https://github.com/ohmyform/ui/commit/ca5edbbb3ba272bb8429b0fe320d1ffd4ec170ce - will be part of next release
