### ISSUE TITLE
Docker-Compose example configs should contain `restart` policy

### ISSUE THREAD

**Issue by ccoenen** [ohmyform/ohmyform#164]
Currently, the [examples](https://github.com/ohmyform/ohmyform/tree/9c58d92aee4d9d2ac8371ca9d1a6cb79c5d9ed28/examples) all do not feature a [restart](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart) rule. This means, that containers do not automatically get recreated on restart. (`restart: no` is the default when nothing is specified).

I think, it would be a good idea to have `restart: unless-stopped` in all of the examples, because this is what is most commonly recommended in production.

**Comment by wodka** [comment]
good point

**Comment by wodka** [comment]
fixed in https://github.com/ohmyform/ohmyform/commit/912be0bc3869ba8dffaecf57f1c6041110b5a694
