### ISSUE TITLE
First Party Docker Image

### ISSUE THREAD

**Issue by benyanke** [ohmyform/ohmyform#168]
#### About the Feature

I would like to propose a public first-party docker image to be built and maintained as part of the release process. Nearly all of the work is done, as a Dockerfile and docker-compose.yml file exists in the repo, it's simply the additional step of adding the checklist or CI to generate a public image in an image registry so that people can use it and not need to build their own.

**Comment by benyanke** [comment]
Cool! mind if I submit a PR with some additional docker information and docs?

**Comment by wodka** [comment]
yes please :)
