### ISSUE TITLE
Unable to delete form (1.0.3)

### ISSUE THREAD

**Issue by decentral1se** [ohmyform/ohmyform#181]
#### What's this issue about?

![image](https://user-images.githubusercontent.com/1991377/168078465-11315f85-b259-4a87-a70c-1c3ee8b6a28c.png)

> 2022-05-12T12:49:06.047991595Z {"level":50,"time":1652359746032,"pid":68,"hostname":"6a0d482026f2","req":{"id":31,"method":"POST","url":"/graphql","query":{},"params":{"0":"graphql"},"headers":{"host":"foo.com","x-real-ip":"10.0.1.7","x-forwarded-for":"10.0.0.2, 10.0.1.7","x-forwarded-proto":"http","connection":"upgrade","content-length":"163","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","accept":"*/*","accept-encoding":"gzip, deflate, br","accept-language":"en-GB,en-US;q=0.9,en;q=0.8","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOlsidXNlciIsImFkbWluIiwic3VwZXJ1c2VyIl0sInN1YiI6MSwiaWF0IjoxNjUyMzU5NTM0LCJleHAiOjE2NTIzNzM5MzR9.Cnn2PFSt3H2lSIhp5gwdsa89KxzWcTqltj_mpIdvPJA","content-type":"application/json","dnt":"1","origin":"https://foo.com","referer":"https://foo.com/admin/forms","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Linux\"","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","x-forwarded-host":"survey.biobulkbende.org","x-forwarded-port":"443","x-forwarded-server":"3f377d4bf04c"},"remoteAddress":"::ffff:127.0.0.1","remotePort":34422},"context":"ExceptionsHandler","err":{"type":"Error","message":"SQLITE_CONSTRAINT: FOREIGN KEY constraint failed","stack":"QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed\n    at QueryFailedError.TypeORMError [as constructor] (/usr/src/api/node_modules/typeorm/error/TypeORMError.js:9:28)\n    at new QueryFailedError (/usr/src/api/node_modules/typeorm/error/QueryFailedError.js:13:28)\n    at Statement.handler (/usr/src/api/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:117:38)\n    at Statement.callbackTrampoline (node:internal/async_hooks:130:17)"},"msg":"SQLITE_CONSTRAINT: FOREIGN KEY constraint failed"}

#### Expected behavior

- Deletes form

#### Actual behavior

- Does not delete form

#### Steps to reproduce

- Create a form
- Try to delete the form

#### Environment

Docker deployment, `ohmyform/ohmyform:1.0.3`, configs in https://git.coopcloud.tech/coop-cloud/ohmyform (sqlite db)

**Comment by MacBadger** [comment]
I have the same issue, and creating further forms doesn't help. In my case it is the second form of three so far. Equally i tried making it not live, still couldn't delete

**Comment by pietru2004** [comment]
I have this issue...

**Comment by wodka** [comment]
this was coming from not deleting the visitors first - fixed in https://github.com/ohmyform/ohmyform/commit/2c9e1d3de04fccc4b0855c9975a394e751550873
