### ISSUE TITLE
I cannot delete submissions?

### ISSUE THREAD

**Issue by IITuxtmuxII** [ohmyform/ohmyform#186]
#### What's this issue about?
I cannot delete submissions?

#### Expected behavior
can delete submission.

#### Actual behavior
can not delete submission.

#### Steps to reproduce
just install it
#### Environment
Ubuntu 20.04 docker

**Comment by Auto-Key** [comment]
I also have the same issue. I like how lightweight this is but being unable to delete submissions is very important.

**Comment by wodka** [comment]
![image](https://github.com/ohmyform/ohmyform/assets/385731/b3c1fa88-3209-430a-9a8b-93318a60cddb)

adding now a delete button :)
