### ISSUE TITLE
Update branding on Website and Logo stock.

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#19]
![screenshot](https://cdn.discordapp.com/attachments/140198727435419648/599066555325612036/logo.jpg)
![screenshot](https://cdn.discordapp.com/attachments/140198727435419648/599066575064137759/preview.png)
![screenshot](https://cdn.discordapp.com/attachments/140198727435419648/599068554045816832/favicon.png)
![screenshot](https://cdn.discordapp.com/attachments/140198727435419648/599069016165974024/e28ab810ed16eb1451d741d42bbbebf2.png)

We really need to get the branding updated everywhere possible so we can start recording new gif/webm tutorials asap.

**Comment by Leopere** [comment]
Logo stock is here
https://cdn.discordapp.com/attachments/140198727435419648/599070106190086144/favicon2.psd
https://cdn.discordapp.com/attachments/140198727435419648/599070108903800842/favicon.psd
https://cdn.discordapp.com/attachments/140198727435419648/599070110434721792/logo.psd

**Comment by mkotamies** [comment]
I'll add favicon and make a PR

**Comment by wodka** [comment]
done
