### ISSUE TITLE
Docker compose fails: "executor failed running [/bin/sh -c yarn install --frozen-lockfile]: exit code: 1"

### ISSUE THREAD

**Issue by Nabinsharma123** [ohmyform/ohmyform#191]
#### What's this issue about?

When I run `docker-compose up -d`
after running sometime it showing me this:-

```
=> ERROR [api  7/10] RUN yarn install --frozen-lockfile                                                        
 => ERROR [ui 6/8] RUN yarn install --frozen-lockfile
------
 > [api  7/10] RUN yarn install --frozen-lockfile:
#13 6.656 yarn install v1.22.19
#13 7.629 [1/4] Resolving packages...
#13 8.793 [2/4] Fetching packages...
#13 131.8 info There appears to be trouble with your network connection. Retrying...
#13 165.3 info There appears to be trouble with your network connection. Retrying...
#13 187.0 error An unexpected error occurred: "https://registry.yarnpkg.com/jsonc-parser/-/jsonc-parser-3.0.0.tgz: connect EHOSTUNREACH 104.16.26.35:443".
#13 187.0 info If you think this is a bug, please open a bug report with the information provided in "/usr/src/api/yarn-error.log".
#13 187.0 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

```
executor failed running [/bin/sh -c yarn install --frozen-lockfile]: exit code: 1
ERROR: Service 'ohmyform' failed to build : Build failed
```

#### Expected behavior
run `docker-compose up -d` without errors

#### Actual behavior
executor failed running [/bin/sh -c yarn install --frozen-lockfile]: exit code: 1

#### Steps to reproduce
```
git clone https://github.com/ohmyform/ohmyform.git
cd ohmyform
git submodule update --init
docker-compose up -d

```

#### Environment
Windows 10, node v16.13.1

**Comment by shashank2000** [comment]
@Nabinsharma123 how did you fix this?

**Comment by Nabinsharma123** [comment]
I run this command

yarn install --network-timeout 1000000

And then rerun the docker compose

**Comment by Justuser3310** [comment]
How do you run this command in docker container?

I can't run, because it always "restarting"

**Comment by Nabinsharma123** [comment]
> How do you run this command in docker container?
> 
> I can't run, because it always "restarting"

Stop the previous docker compose command Then run
 yarn install --network-timeout 1000000
Then rerun the docker compose
It will took couple of "restarting "
