### ISSUE TITLE
Login not possible - wrong user/password (admin/admin)

### ISSUE THREAD

**Issue by eugeis** [ohmyform/ohmyform#194]
Hello,

<img width="1017" alt="Screenshot 2022-08-29 at 13 36 31" src="https://user-images.githubusercontent.com/609363/187193953-7d4e8424-5dcf-4d75-aeaf-37eb2de554e5.png">

It is deployed with docker-compose [minimal](https://github.com/ohmyform/ohmyform/blob/master/examples/docker_minimal/docker-compose.yml).

here are logs and content of user table
[ohmyform-docker-logs.txt](https://github.com/ohmyform/ohmyform/files/9444205/ohmyform-docker-logs.txt)
[sqlite_user_table.txt](https://github.com/ohmyform/ohmyform/files/9444208/sqlite_user_table.txt)

There is also a API error in UI

<img width="943" alt="Screenshot 2022-08-29 at 13 35 37" src="https://user-images.githubusercontent.com/609363/187193992-a5bff637-25ea-4178-b754-e2d13d042857.png">

Any ideas?

Thanks

**Comment by withpublic** [comment]
I think it is happening because of misconfiguration of Apollo client. If you see in the logs, it is trying to reach http://localhost:4000/graphql, instead of http://localhost:4100/graphql. I changed client.ts file to read 

new HttpLink({
          uri: "http://localhost:4100/graphql",
        }),

**Comment by heyakyra** [comment]
> misconfiguration of Apollo client

These are the only values we can pass in to the container: https://github.com/ohmyform/api/blob/master/doc/environment.md so what would be the correct configuration? 

It looks like many others have hit this, but nobody has responded. Should we merge this ticket into https://github.com/ohmyform/ohmyform/issues/122#issuecomment-1433964118 and re-open the original?

**Comment by wodka** [comment]
![image](https://github.com/ohmyform/ohmyform/assets/385731/ff8d7e20-a598-4415-96eb-4737d1d41e11)


If you have the api running at a different location you can configure it through the ENDPOINT env: https://github.com/ohmyform/ohmyform/blob/master/ui/doc/environment.md
