### ISSUE TITLE
User Role cannot be changed from the UI

### ISSUE THREAD

**Issue by haivala** [ohmyform/ohmyform#198]
#### What's this issue about?
User Role cannot be changed from the UI. The error is that user email is in the use already and even if the email is changed with the role the Role of a user does not change. 

#### Expected behavior
User Role could be changed

#### Actual behavior
It throws a error and the log says the users email is in use already.
```
context":"ExceptionsHandler","err":{"type":"Error","message":"email already in use","stack":"Error: email already in use\n    at UserUpdateService.update (/usr/src/app/dist/service/user/user.update.service.js:37:23)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async UserUpdateMutation.updateUser (/usr/src/app/dist/resolver/user/user.update.mutation.js:38:9)\n    at async target (/usr/src/app/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)\n    at async Object.updateUser (/usr/src/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)"},"msg":"email already in use"}
```

#### Steps to reproduce
1. Make SuperAdmin with a deployment
2. Make normal user from the frontend.
3. Log in with the superadmin and try to change users role

#### Environment
docker-compose stack.

**Comment by yannickh2** [comment]
We have a similar problem: Screenshot attached. Trying to change from User to Admin throws an error.
![CannotSaveUserasAdmin](https://github.com/ohmyform/ohmyform/assets/38760521/05363cbc-1076-4b67-858b-6b747fc2db46)

**Comment by MacBadger** [comment]
yep, same issue here

Only one user registered- the original admin
Got new user to signup
Attempted to change user > admin

"could not update user"

**Comment by ulfgebhardt** [comment]
Working fix available here https://github.com/ohmyform/api/pull/49

**Comment by wodka** [comment]
thx for the fix - just applied it to the api
