### ISSUE TITLE
not sending email notifications (heroku)

### ISSUE THREAD

**Issue by googlinggreg** [ohmyform/ohmyform#200]
Hello, I have been using an instance of ohmyform in Heroku and it runs well for the most part. However, I'm unable to receive notifications via email after setting up the details in the settings. It may be my lack of expertise, but do I need to set up another app or something on heroku in order to send email out properly? Thanks.

**Comment by wodka** [comment]
do you have an SMTP Server setup?

**Comment by googlinggreg** [comment]
I tried installing a couple of apps like cloudmailin, but I couldn't figure
out if some additional configuration or anything was required.

**Comment by wodka** [comment]
https://github.com/ohmyform/api/blob/c2c421baa6f41e4e6fb812fa2978956aaf7aa0dd/doc/environment.md#mailing

do you have the SMTP environment variables setup for it?

**Comment by googlinggreg** [comment]
Right now I have that set to an external site I use for my other website
and hosting. If I'm using something within heroku, is there another address
I should be pointing it to? i.e. localhost:something

**Comment by satoshinotdead** [comment]
> SMTP environment variables
Setting mailhog we can set our smtp mailing service variables?

**Comment by satoshinotdead** [comment]
What about mailgun? That's our service (very good and affordable one).
