### ISSUE TITLE
Turkish Language Localization

### ISSUE THREAD

**Issue by klconur** [ohmyform/ohmyform#208]
#### What's this issue about?

Turkish Localization

#### About the Feature

I have joined to lokalise project but could not find the Turkish language section. Can you add it please so I can contribute to Turkish localization? Best.

**Comment by wodka** [comment]
Added Turkish just now :)

**Comment by klconur** [comment]
Hi @wodka,

I could not find it on https://app.lokalise.com/project/379418475ede5d5c6937b0.31012044/?view=single&reference_lang_id=640&single_lang_id=714
