### ISSUE TITLE
User Tiers

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#21]
Admin, Moderator, User.

Admin meaning one that can modify, view, submit and delete everything.
Moderator one that can modify, view, submit, and delete some things.
User one that can view and submit some things.

Ultra-simple Discord-Esque permissions system might be nice long term but not likely necessary right now.

**Comment by wodka** [comment]
https://github.com/ohmyform/api/blob/master/doc/roles.md are now implemented in the backend
