### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by gustavi** [ohmyform/ohmyform#216]
Hello,

The project did not receive any sign of life for months. Is it considered dead/deprecated?

Regards,

cc @wodka

**Comment by wodka** [comment]
Hi - I'm blocked for the last few months with work :/ hoping for this to change in the near future again!

**Comment by yannickh2** [comment]
any news on this?

**Comment by p-jones** [comment]
?

**Comment by timmwille** [comment]
Do you need help?

**Comment by LitefootGG** [comment]
> Do you need help?

If your interested in contributing stop by the public Discord and ping either LitefootGG or Leopere, we are looking for people to assist with various aspects of the project, there might be something on the roadmap that you would find worth your time. :)

**Comment by Qodestackr** [comment]
I am interested to contribute to this. Cloned the repo. Let me know if this is a bug and I can help out:
` => ERROR [api  6/10] RUN touch /usr/src/api/src/schema.gql && chown 9999:9999 /usr/src/api/src/schema.gql`

**Comment by Qodestackr** [comment]
> > Do you need help?
> 
> If your interested in contributing stop by the public Discord and ping either LitefootGG or Leopere, we are looking for people to assist with various aspects of the project, there might be something on the roadmap that you would find worth your time. :)

I'm interested.

**Comment by wodka** [comment]
any PR's are welcome - the project now also has a single repo so it should be easier to propose changes

**Comment by gustavi** [comment]
I close this issue since it's not relevant anymore right now.

**Comment by Qodestackr** [comment]
Project seems too complex to render a form 😯
