### ISSUE TITLE
Self Promotion

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#22]
We need to consistently link to how to contribute/work with to OhMyForm.  If people haven't debranded OhMyForm by option for deployment in their environment make sure to link back to our contributions page/website whatever we prefer.

My idea here is to encourage a full circle of github/website > dev > users > contributions conversions.  The users should intuitively know how to get back to us if the DevOps deploying OhMyForm choose to thank us via letting us have something similar to the "View on Github" red tape banner thing on the top right of some projects.

**Comment by Leopere** [comment]
Leaving a checkbox which encourages the sysadmin to allow linkback to OhMyForm's How To Contribute and an ENV variable boolean that would allow the sysadmin to turn it off via docker-compose or whatever would be wonderful.

**Comment by wodka** [comment]
HIDE_CONTRIB=TRUE will in the api will hide the omf badge
