### ISSUE TITLE
Language Support Mandarin

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#27]
Metrics collection reports that it would be smart to support Mandarin as well to increase adoption.

**Comment by 7Ji** [comment]
I've made a translation patch which replaces the original English language file to function, since I can't locate where to define the language list. Don't know if that is acceptable and legal. 
https://github.com/7Ji/OhMyForm_Hanization
If offensive I would delete it

**Comment by wodka** [comment]
@7Ji thank you for the work - could you add it as a PR and add the language here:

`config/express.js ~ supportedLanguages = [...]`

The reason it didn't show up for you is probably because the optimized didn't contain it (requires a rebuild of the assets) - this is not well documented right now.

**Comment by Leopere** [comment]
We absolutely want to have proper language files please keep up the good work!

**Comment by wodka** [comment]
@7Ji would it be possible that you look over the translations for the new ui? 

https://app.lokalise.com/public/379418475ede5d5c6937b0.31012044/

**Comment by 7Ji** [comment]
Sorry but i'm currently busy preparing for my end-term exams these days. I
will get my hands on the translation once I finish my exams about a week
later.

Michael Schramm <notifications@github.com> 于2020年6月9日周二 上午1:52写道：
