### ISSUE TITLE
Demonstration Mode envvar flag.

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#30]
It would be good to see a Demo Mode where the app could respond differently and have notifications on the login page with the login creds for root//root and user//user accounts.

**Comment by wodka** [comment]
I think we should add several settings:

- `DEFAULT_ROLE` -> `admin` | `superuser` | `user` - with `user` being the default, making it possible that new users can create their own forms after creating
- `LOGIN_NOTE` -> markdown for Login Page, to show info text on login page

**Comment by wodka** [comment]
![image](https://user-images.githubusercontent.com/385731/84363750-75228d00-abcf-11ea-91d3-1df753fbb1f7.png)
