### ISSUE TITLE
Add captions to buttons

### ISSUE THREAD

**Issue by karser** [ohmyform/ohmyform#33]
Probably translation is missing or broken

Here is Add/remove question:
![image](https://user-images.githubusercontent.com/1675033/64105122-3fb65c80-cd7e-11e9-93c0-f03dd1b56fb4.png)

**Comment by menikhilpandey** [comment]
Hi, I would like to work on this, can you elaborate the issue?

**Comment by siikasmaa** [comment]
I can work on this 😊

**Comment by wodka** [comment]
the new ui no longer has this problem
