### ISSUE TITLE
[error] Asset /static/lib/font-awesome/css/font-awesome.min.css not found

### ISSUE THREAD

**Issue by karser** [ohmyform/ohmyform#35]
Steps to reproduce:
On newly created survey go to design tab and open the console

Refused to apply style from 'https://ohmyform.mydomain.com/static/lib/font-awesome/css/font-awesome.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

![image](https://user-images.githubusercontent.com/1675033/64106082-28786e80-cd80-11e9-9e1e-06f4f1f254b2.png)

**Comment by wodka** [comment]
no longer applies - thx for reporting
