### ISSUE TITLE
[docker] surveys are lost after down/up

### ISSUE THREAD

**Issue by karser** [ohmyform/ohmyform#37]
I use this config https://github.com/ohmyform/ohmyform/blob/master/docker-compose.yml plus traefik labels. Here is my docker config https://github.com/ohmyform/ohmyform/issues/36

Steps to reproduce:
- login as root, create some surveys
- docker-compose down && docker-compose up
- login as root once again
![image](https://user-images.githubusercontent.com/1675033/64106845-b43eca80-cd81-11e9-8302-e25ae6bc8c87.png)

The mongodb data is preserved
![image](https://user-images.githubusercontent.com/1675033/64106895-d5072000-cd81-11e9-9af2-722581fbd8bc.png)

**Comment by wodka** [comment]
Thanks for reporting this - it should persist the entries...
