### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by wodka** [ohmyform/ohmyform#38]
## Description

recreate the complete api in nestjs - idea is to have it working and still be compatible with the current frontend. 

## Motivation and Context

https://github.com/ohmyform/ohmyform/issues/16
https://github.com/ohmyform/ohmyform/issues/37
https://github.com/ohmyform/ohmyform/issues/36
https://github.com/ohmyform/ohmyform/issues/35
https://github.com/ohmyform/ohmyform/issues/34
https://github.com/ohmyform/ohmyform/issues/23
https://github.com/ohmyform/ohmyform/issues/19
https://github.com/ohmyform/ohmyform/issues/15

## Types of changes

rewrite, **the mongo structure has to stay exactly the same!**

## Checklist:

- [x] create schema with mongoose
- [x] add authentication
- [x] add registration
- [x] authentication synchronisation between old and new code
- [x] form editing
- [x] form submission
- [x] user editing
- [x] form view

**Comment by almereyda** [comment]
It appears this is the high-level issue for #40.

**Comment by Leopere** [comment]
Thanks for making the connection @almereyda

**Comment by wodka** [comment]
https://github.com/ohmyform/ohmyform/pull/87

**Comment by wodka** [comment]
will continue as separate issues as development is already in master
