### ISSUE TITLE
Get the Dockerfile set to run the application in a restricted user as opposed to the current run as root by default.

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#43]
Running applications as the root user is never recommended in production.  Since this appliance is still effectively a preview beta release we are currently running it as an unrestricted Root user however ideally we should be focusing on a restricted user with the capacity of correcting its own file permissions.

**Comment by ahmedkrmn** [comment]
Can I work on this one?

**Comment by Leopere** [comment]
That was the fastest I've dropped a Hacktoberfest issue to getting a reply in the history of hacktoberfest I swear good job!

Now I would say please consider filing a PR for this it will save me loads of time testing and writing it later!
