### ISSUE TITLE
As per Line one of this specific committed version of the docker-compose.yml we need more deployment examples.

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#44]
It appears as though we need a version stored somewhere in this repository wherein we have a dev environment example of deployment of OhMyForm.
The TODO comment can be removed [from here](https://github.com/ohmyform/ohmyform/blob/master/docker-compose.yml#L1) when it's completed.

**Comment by wodka** [comment]
https://github.com/ohmyform/ohmyform/tree/master/examples
