### ISSUE TITLE
Favicon is missing from the website

### ISSUE THREAD

**Issue by mkotamies** [ohmyform/ohmyform#46]
#### What's this issue about?
Favicon is in the project but it's not visible on the website

#### Expected behavior
User should see favicon in the browser tab

#### Actual behavior
User sees placeholder image

#### Steps to reproduce
Go to https://ohmyform.com/

#### Environment
Production

**Comment by Leopere** [comment]
Also @mkotamies https://ohmyform.com is in fact actually https://github.com/ohmyform/website so make sure to look into doing it on both.

**Comment by mkotamies** [comment]
@Leopere Thanks, I missed that!

**Comment by wodka** [comment]
website and form have default icons as far as I can tell right now.
