### ISSUE TITLE
Missing links in README.md table of contents

### ISSUE THREAD

**Issue by siikasmaa** [ohmyform/ohmyform#47]
#### What's this issue about?
README.md table of contents has links to missing content, i.e. "How to contribute" and "On the Roadmap for v1.0.0".

#### Expected behavior
Clicking on the link in table of content should redirect to the content.

#### Actual behavior
Nothing happens.

#### Steps to reproduce
Click one of the aforementioned links in the table of contents.

**Comment by marcelscruz** [comment]
Hey.

Should be an easy fix, I'll give it a go.

**Comment by Leopere** [comment]
thanks for your follow through!
