### ISSUE TITLE
Trying to install dependencies locally causes post-install bower script to fail

### ISSUE THREAD

**Issue by petmat** [ohmyform/ohmyform#49]
When I tried running `npm install` in the root directory locally after cloning the repository the bower install threw an error:

```
bower                     ECONFLICT Unable to find suitable version for jquery
```

Not sure if this is required to get the app running locally but since it looked like a genuine error I decided to report it. I might even have a fix for this that I will make a PR of so that you can decide whether you want it or not.

**Comment by wodka** [comment]
thanks for reporting and fixing
