### ISSUE TITLE
Error 500 on demo instance http://demo.ohmyform.com

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#5]
#### What's this issue about?

Attempting to load demo instance results in Error 500
http://demo.ohmyform.com/

#### Expected behavior

Get presented with the login page.

#### Actual behavior

Error 500

#### Steps to reproduce

Check out the demo instance at aforementioned URL.

#### Environment

Hosted within the Docker container.

**Comment by wodka** [comment]
Is this the image from dockerhub?

**Comment by Leopere** [comment]
Confirmed yes. http://demo.ohmyform.com:82

**Comment by wodka** [comment]
:/ the whole reason is the subdomain logic...

to have it working please set the environment `SUBDOMAINS_DISABLED = TRUE`
