### ISSUE TITLE
Dockerfile linting

### ISSUE THREAD

**Issue by Leopere** [ohmyform/ohmyform#52]
https://github.com/hadolint/hadolint/wiki/DL4000 for the now deprecated `MAINTAINER` directive can be replaced with `LABEL maintainer`

https://github.com/hadolint/hadolint/wiki/DL3016 for `npm` and `apk add` we should likely be pinning versions, its more maintenance for us as the repository maintainers but its smart long term as we won't break peoples installations in the future if we do it this way.  Either this or we should ensure to get some CI/CD tests setup to validate that what we push is 100%

**Comment by Leopere** [comment]
Also ensuring that we reduce layers as much as possible is always a plus but once this one is closed the Dockerfile is relatively 1.0 ready.

**Comment by mhmoosazadeh** [comment]
@Leopere Hi, Do you mean you want to have a multistage Dockerfile? A step for checking the project test? If yes, I think I can help with it.

**Comment by Leopere** [comment]
@mhmoosazadeh thanks for your quick reply, thats not exactly the priority here it was more a mention to the fact that ultimately that would be ideal.   However, in the mean time we could just have a couple of tested pinned packages.  Aka whatever is the latest possible release version of the packages required to run OhMyForm those are the ones that should be pinned in the Dockerfile.

**Comment by mhmoosazadeh** [comment]
> @mhmoosazadeh thanks for your quick reply, thats not exactly the priority here it was more a mention to the fact that ultimately that would be ideal. However, in the mean time we could just have a couple of tested pinned packages. Aka whatever is the latest possible release version of the packages required to run OhMyForm those are the ones that should be pinned in the Dockerfile.

Good, So please assign it to me.

**Comment by Leopere** [comment]
Thanks for the PR
