### ISSUE TITLE
full stand alone documentation

### ISSUE THREAD

**Issue by muzzol** [ohmyform/ohmyform#62]
#### About the Feature
I can't use docker on all my clients so I would like to see a full installing documentation.

Most environments already got DB and mail servers so there's no need to duplicate work.

Even if is specific to a distro it's better than nothing and the community will fill the gaps when needed.

**Comment by Leopere** [comment]
Here's the unsupported documentation https://github.com/ohmyform/ohmyform/blob/master/Dockerfile Dockerfiles that are written well should effectively be documentation on how to not use Docker.

**Comment by Leopere** [comment]
Just for the future can we link in where it’s located now?

**Comment by wodka** [comment]
Same Link to the Dockerfile :)
