### ISSUE TITLE
Discord invite link expired

### ISSUE THREAD

**Issue by samnazarko** [ohmyform/ohmyform#63]
Hi,

Sorry -- this is probably the wrong place, but couldn't find anywhere else on the Contact page. 
I tried to join your Discord project but I am told the link has expired.

Cheers

Sam

**Comment by Leopere** [comment]
Sorry about that have this one.  https://discord.gg/MJqAuAZ

**Comment by samnazarko** [comment]
Still no joy unfortunately. Not sure why

**Comment by Leopere** [comment]
Just confirmed it's working sounds like it's on your side, I'm willing to keep discussing this but I'm going to mark this invalid and close it.

**Comment by samnazarko** [comment]
Sorted. Had to verify my account with a phone number it seems. After logging in, I was able to join. Sorry for the noise.

**Comment by Leopere** [comment]
Aye, no worries!  Glad you made it.
