### ISSUE TITLE
Icons are not displayed in a fresh instance

### ISSUE THREAD

**Issue by Lamera** [ohmyform/ohmyform#64]
#### What's this issue about?

Icons aren't showing up.
![grafik](https://user-images.githubusercontent.com/19840658/69851773-d06bde00-1282-11ea-88a5-891091bfd0b2.png)
![grafik](https://user-images.githubusercontent.com/19840658/69851960-4ff9ad00-1283-11ea-9343-85dc500f7e6b.png)

#### Expected behavior

The Icons from the rating and the trash icon to delete an entry in the form should be displayed.

#### Actual behavior

There aren't any icons on the site. Do I something wrong?

#### Steps to reproduce

I followed this steps on a freshly installed ubuntu server 18.04:

>     Step One: git clone https://github.com/ohmyform/ohmyform.git
>     Step Two: Modify anything you want to in the source.
>     Step Three: cd ohmyform
>     Step Four: docker-compose up -d
>     Step Five: docker-compose ps

#### Environment

Ubuntu Server 18.04.3

**Comment by securisec** [comment]
@Lamera  did you ever solve this? I am facing the same issue.

**Comment by Lamera** [comment]
No, I didn‘t solve my problem until now. Do you have an idea why this is happening?

**Comment by securisec** [comment]
@Lamera I didnt. Seems like a lot is broken in the project atm. I moved on to using something else.

**Comment by ndom91** [comment]
The issue is the `font-awesome.min.css` file is not being loaded due to MIME type checking. It's somehow being sent as `text/html`, therefore the browser wont apply it as a stylesheet, and therefore none of the icons will work.

**Comment by luixal** [comment]
I'm not sure, but think more stylesheets may be affected by this. In may case, in addition to missing icons, scaling sucked:

![image](https://user-images.githubusercontent.com/615268/78447042-f4e52600-7679-11ea-97af-4641e28b5c6f.png)

![image](https://user-images.githubusercontent.com/615268/78447104-f878ad00-7679-11ea-8e71-f6c4d1d5aa62.png)

**Comment by wodka** [comment]
the new ui should no longer have this problem
