### ISSUE TITLE
Focus first field

### ISSUE THREAD

**Issue by wodka** [ohmyform/ohmyform#65]
#### What's this issue about?

when opening a form the first field should focus

#### Expected behavior

focus first field of form

#### Actual behavior

no focus to any field

#### Steps to reproduce

create a form with at least one field, open the page to edit the entries

**Comment by JesusPerez** [comment]
I could fix this by adding:
.field-directive:nth-child(1) { opacity: 1;}
in public/modules/forms/base/css/forms.css

**Comment by BlueSquad-dev** [comment]
I would accept any PR's that you might be willing to contribute, no need to get authorization from us just submit a PR and tell us why you think it's useful or any good and we're golden on a merge!

**Comment by Leopere** [comment]
I would accept any PR's that you might be willing to contribute, no need to get authorization from us just submit a PR and tell us why you think it's useful or any good and we're golden on a merge!

**Comment by phips28** [comment]
same here on safari. Chrome works.
After a scroll, the first question displays correctly

**Comment by wodka** [comment]
it is now working for the new card layout of forms.

**Comment by wodka** [comment]
should now also work for slider forms
