### ISSUE TITLE
examples page not found

### ISSUE THREAD

**Issue by davidak** [ohmyform/ohmyform#66]
#### What's this issue about?

The readme links to https://ohmyform.com/examples but "This does not exist".

#### Expected behavior
no broken links

#### Actual behavior
broken links

#### Steps to reproduce
click on link

#### Environment

- NixOS 19.09.1685.e9ef090eb54 (Loris)
- Chromium 78.0.3904.108
- on a Thinkpad X230
- what else do you need?

**Comment by JonasWinter** [comment]
Since [https://ohmyform.com/](https://ohmyform.com/) does not provide any examples yet, I thin there are basically two options:
1. Remove the link
2. Link the [old examples at tellform](https://www.tellform.com/examples) with the hint, that these are old examples.

What's the preference?

**Comment by davidak** [comment]
I think linking to a different project that might differ is not a good idea. So we should remove it until we have up to date examples or best a demo survey.

**Comment by wodka** [comment]
I cannot find the link anymore - therefor closing the issue
