### ISSUE TITLE
Plesk installation

### ISSUE THREAD

**Issue by digitall-it** [ohmyform/ohmyform#68]
#### What's this issue about?
I would like to make this software work by not issuing a docker compose. Instead, I would like to download the core image from the Docker repository via the Plesk interface, and connect it to local instances of Redis, MongoDB and so on.

#### Expected behavior
I would expect to have an environment variable that I could customize with the address of the MongoDB database.

#### Actual behavior
Seems to be hardwired, or not published.

#### Steps to reproduce
Install the docker image in a Plesk interface, then try to run it. It will not find the MongoDB database, so if you start one you'll want to wire it up but it's not in the env vars of the ohmyform docker image.

#### Environment
Plesk Onyx 17.5 on Centos 7.

#### About the Feature
I would like to receive some help in making this work on Plesk, a web panel used on a large percentage of web servers worldwide. This would mean that OhMyForm could work in a shared environment much easier.

**Comment by wodka** [comment]
for this you could set the env variables (http://ohmyform.com/docs/env/)
* MONGODB_URI
* REDIS_URL
