### ISSUE TITLE
Rating option not working

### ISSUE THREAD

**Issue by uditgogoi** [ohmyform/ohmyform#69]
#### What's this issue about?
When I am selecting rating as the option, nothing is shown

#### Expected behavior
On selection of Rating as form type, and 10 steps, I should be able to get 10 clickable shapes based on shape selection. 

#### Actual behavior
Nothing is shown below the Title

#### Steps to reproduce
```
1. Launch ohmyform using docker and run it locally
2. Create a new form
3. Select Rating on Add New Field.
4. Try changing the number of steps and save the form.
5. View Form 
```

#### Environment
OS-X

**Comment by Niii** [comment]
Same here on Debian10

**Comment by ndom91** [comment]
See my answer here: https://github.com/ohmyform/ohmyform/issues/64

The icons for the rating question type are not being loaded because the `font-awesome` css file is not loading correctly (MIME type checking error)

**Comment by phips28** [comment]
CSS not found it says.
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/3694800/76247363-b6f20f00-623f-11ea-87f1-acc089053168.png">

testing on the demo instance: https://demo.ohmyform.com/#!/forms/5dd1a2c7aabff58075f786c2/admin/create

**Comment by wodka** [comment]
no longer applies - thx for reporting
