### ISSUE TITLE
Signup Not Working - Both on main website and Docker build

### ISSUE THREAD

**Issue by monizb** [ohmyform/ohmyform#70]
#### What's this issue about?

The signup page does not work and it when signup is clicked, it shows a message: 
"Couldn't complete registration due to errors:
{"message":""}"

When I try to login, it says user does not exist.
When I try to reset password, it says the user's email is not verified, but I did not get any email

#### Expected behavior

Sign up the user without errors and send a verification email

#### Actual behavior

Throwing error message and no email being sent

**Comment by debmaj2** [comment]
+1

**Comment by aabril** [comment]
+1

**Comment by OSevangelist** [comment]
same here +1

**Comment by fortydegrees** [comment]
+1

**Comment by calebfreeman** [comment]
+1

**Comment by aantix** [comment]
@wodka Any ideas?  Looks like there's been a ton of time invested here, would love to evaluate OhMyForm.

**Comment by wodka** [comment]
fixed in https://github.com/ohmyform/ohmyform/pull/77

it is related to an invalid email config, the moment the config is set it works
