### ISSUE TITLE
Analytics showing zero

### ISSUE THREAD

**Issue by phips28** [ohmyform/ohmyform#72]
#### What's this issue about?
Analytics showing zero even though I submitted responses.

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/3694800/76247122-54990e80-623f-11ea-9633-c1e355b4e11b.png">

#### Expected behavior
Show correct analytics numbers.

#### Actual behavior
Zero

#### Steps to reproduce
https://demo.ohmyform.com/#!/forms/5dd1a2c7aabff58075f786c2/admin/analyze
(user: root, pw: root)

#### Environment
https://demo.ohmyform.com/#!/forms/5dd1a2c7aabff58075f786c2/admin/analyze

**Comment by wodka** [comment]
no longer applies - thx for reporting

**Comment by rparree** [comment]
Hi,

A question, where can i find this in the current project. I am also trying to find it in the next.js project for the ui, but can't find anything about a "analyse" page for forms. We are looking into using this project but need a "reporting" or analytics on the submitted data. The screen-shot looks very promising.

tx.,

**Comment by wodka** [comment]
hi @rparree - right now the new ui only has a very basic list of submissions

you are welcome to create a PR to add this kind of reporting.
