### ISSUE TITLE
Where to find a release?

### ISSUE THREAD

**Issue by tobidwest** [ohmyform/ohmyform#73]
Hi,

where can I find a ready build to upload via ftp?

Thanks for helping out!

**Comment by wodka** [comment]
you will need a system with docker installed, or a root server where you can setup the system yourself

**Comment by tobidwest** [comment]
Sorry, we're on shared hosting, so I cannot do so. Any possibility of
getting a *.zip file?

**Comment by Leopere** [comment]
@tobidwest Dockerfiles are effectively installation instructions.  Some instructions are a little less straight forward but you could probably achieve an installation by reading through https://github.com/ohmyform/ohmyform/blob/master/Dockerfile

**Comment by Leopere** [comment]
Otherwise, you're welcomed to try out https://demo.ohmyform.com to see if it suits your needs.

**Comment by tobidwest** [comment]
Hi, thanks for getting back. Unfortunately, I'm not that experienced. Any chance of a ready release asset becoming available in the future?

**Comment by wodka** [comment]
the system does not work as an asset - you will need additional services to spin up on your hosting service
