### ISSUE TITLE
Associate a spreadsheets to the forms

### ISSUE THREAD

**Issue by jibe-b** [ohmyform/ohmyform#76]
#### What's this issue about? 
Mainstream services like airtable or google cloud offer both forms & visual databases (spreadsheets).

Do you plan to develop an ad hoc spreadsheet webapp, or do you consider integrating ohmyforms to an existing tool, like [ethercalc](github.com/ether/ethercalc)?

Thanks a lot for the work you've done developping tellforms and ohmyform!

**Comment by wodka** [comment]
currently there is no intent to build a spread sheet - ohmyform should be there to collect information and then to enable you to export the data
