### ISSUE TITLE
Yunohost package or "How to install without Docker"

### ISSUE THREAD

**Issue by Aeris1One** [ohmyform/ohmyform#78]
#### About the Feature

Hi, 
Is it possible to create a Yunohost package for this app ? This will make Yunohost users (about 3000) able to install OhMyForm in two clicks, so having a Yunohost package will help you growing as  all the users of Yunohost will be aware of the existence of OhMyForm and the number of installation will dramatically increase.

If you don't have time to spend with the creation of a such package, I can do it, but I need to know how to install OhMyForm **without** Docker because some (if not all) Yunohost servers doesn't have docker preinstalled and some are incompatible with (ARM and LXC VPS among others).

PS: I'm on the Discord server if you want to discuss about that (@Aeris One#9906)

**Comment by wodka** [comment]
you can take a look at the dockerfile on how to setup the system

additional requirements next to hosting the static files are a nodejs server and mongodb

**Comment by wodka** [comment]
With the new Release this has been simplified: 

For the UI:
https://github.com/ohmyform/ui/blob/master/doc/development.md
For the Backend:
https://github.com/ohmyform/api/blob/master/doc/development.md
