### ISSUE TITLE
Demo page doesn't work

### ISSUE THREAD

**Issue by elfeffe** [ohmyform/ohmyform#80]
The demo on your readme doesn't exist

**Comment by Leopere** [comment]
![https://i.imgur.com/TKNNTuN.png](https://i.imgur.com/TKNNTuN.png)
[https://demo.ohmyform.com/](https://demo.ohmyform.com/) appears to be working for me.  Typically the path in is via the website, I would definitely accept any improvement Pull Requests you submit.

**Comment by elfeffe** [comment]
Yes, this is the commit thatt fix what I said
https://github.com/ohmyform/ohmyform/commit/3e72a094f146233873779c86bc17731fdab00b6e

**Comment by elfeffe** [comment]
Anyway, I can't register
https://gyazo.com/00deede631117c6a11a45ab26ae19d76

**Comment by Leopere** [comment]
Registration is currently on the todo list. It’s a leftover from the
original codebase.

**Comment by elfeffe** [comment]
So it is not possible to see the demos, because you are obliged to login to
see them

**Comment by Leopere** [comment]
The documentation is all on the site if you have a look over at
https://OhMyForm.com you’ll manage to see that there’s details there on
what to do. But the default login which is documented is username: root
with the password: root

**Comment by wodka** [comment]
demo page is up and running with the new ui
