### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by loleg** [ohmyform/ohmyform#81]
Continuing from #32, we should try to get OhMyForm running on Heroku, which was supported by TellForm and is a popular PaaS to quickly deploy the app. The general solution here should also be applicable to similar NodeJS-compatible platforms. In Heroku's case, what we probably need are:

- A working `Procfile`
- An `app.json` with all the required settings and bundled resources
- Some additional documentation, e.g. bringing back "the button"

**Comment by loleg** [comment]
The issue in my [last comment](https://github.com/ohmyform/ohmyform/issues/32#issuecomment-623559132) on #32 was a really [easy fix](https://github.com/schoolofdata-ch/ohmyform/commit/e9fce972a3bb1b16b4432517a4e81e2b2b179f0c). The application deploys and runs without errors. But now I'm stuck looking at a completely blank page, with this in my JavaScript console:

```
The resource from “https://omf-schoolofdata.herokuapp.com/static/lib/font-awesome/css/font-awesome.min.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
omf-schoolofdata.herokuapp.com
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. omf-schoolofdata.herokuapp.com
The resource at “<URL>” was blocked because content blocking is enabled. 2
‘src’ attribute of <script> element is not a valid URI: “http://#{request.hostname}:35729/livereload.js” omf-schoolofdata.herokuapp.com:8:1
Error: [$injector:modulerr] http://errors.angularjs.org/1.7.9/$injector/modulerr?p0=app&…n.ravenjs.com%2F2.3.0%2Fangular%2Fraven.min.js%3A2%3A3806%0A angular.js:99
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.ohmyform.com/api/2/store/?sentry_version=7&se…raven-js%2F2.3.0&sentry_key=XYZABCD. (Reason: CORS request did not succeed).
```

I did make sure that the npm and bower install scripts succeeded. It seems like the grunt task did not run automatically, so I used Heroku's console to run the last part of the Dockerfile, but that did not help.

Maybe we should open a new issue to continue this discussion :)

**Comment by wodka** [comment]
currently there is a really strange way of initialising the whole app. I'm still in the process of fixing this in a huge refactoring to simplify this.

in the Dockerfile you can see the current steps that are needed to build an instance:

```
npm install --only=production \
    && bower install --allow-root -f \
    && grunt build
```

and then to run it `node server.js`

**Comment by loleg** [comment]
Adding `grunt build` to the `postinstall` step in `package.json` resolved my problem, and the app is working! :ice_hockey: :goal_net:

**Comment by loleg** [comment]
One thing I still don't really get is: how to create an admin account. Do we recommend using the `ADMIN_` environment variables on first deployment, or is there a better way besides using the create-admin script?

**Comment by wodka** [comment]
right now this is the only way

**Comment by loleg** [comment]
Great! So setting the variables, waiting for the server to start, and then removing them worked fine.

**Comment by Leopere** [comment]
Closing due to merged PR
