### ISSUE TITLE
Required database is not FSF/OSI/Fedora/Debian Approved

### ISSUE THREAD

**Issue by heyakyra** [ohmyform/ohmyform#86]
MongoDB changed its license to be untenably restrictive. 
>It’s been more than a year when the upstream MongoDB decided to change the license of the Server code. The previous license was GNU Affero General Public License v3 (AGPLv3). However, upstream wrote a new license designed to make companies running MongoDB as a service contribute back to the community. The new license is called Server Side Public License (SSPLv1)
>[...]
>When SSPL was released, Fedora determined that it is not a free software license [...h]ence the Fedora community decided to remove the MongoDB server entirely

https://fedoramagazine.org/how-to-get-mongodb-server-on-fedora/

Many alternatives exist such as Mariadb and PostrgeSQL. It would be nice to switch or at least support another database.

**Comment by wodka** [comment]
Hi @heyakyra 

sadly there is no simple way for us to support a relational database, mongodb is a document storage.

we have the communication done with https://mongoosejs.com/ - if you are willing you can help to further abstract the logic in the api https://github.com/ohmyform/api

**Comment by Leopere** [comment]
I think that the goal of the original comment was more that mongo has lame licensing. Could we use Redis or even Postgres for the document storage?  I know we’re pretty entrenched in mongo so a pivot would be awkward now but maybe even CouchDb I believe could be a drop in replacement for mongo.

**Comment by Leopere** [comment]
https://www.percona.com/software/mongodb/percona-server-for-mongodb This is apparently an AGPL variant of mongo could be a drop in replacement

**Comment by Leopere** [comment]
I'm going to explore potentially dropping in https://hub.docker.com/r/percona/percona-server-mongodb/ instead of the mongodb server if the container deploys nicely. 

PS. @wodka can you DM me on Discord.
PPS. @heyakyra your portfolio website is offline.

**Comment by Leopere** [comment]
I've tested replacing the container image with the percona-server-mongodb container on my local instance and it seemed to run perfectly fine.

**Comment by maxerbox** [comment]
> 
> 
> https://www.percona.com/software/mongodb/percona-server-for-mongodb This is apparently an AGPL variant of mongo could be a drop in replacement

It is still based on MongoDB community edition, so the license is the same. Take a look at https://github.com/percona/percona-server-mongodb

**Comment by Leopere** [comment]
@maxerbox that's a bummer, I wonder what a good alternative would be that would be FSF/OSI/etc. approved with similar data storage.

**Comment by vpicavet** [comment]
PostgreSQL has support for schemaless data with native JSONB support, indexing, JSONPATH and much more : https://www.postgresql.org/docs/current/datatype-json.html

**Comment by Leopere** [comment]
My only concern with postgres is will it scale relatively easily?

**Comment by vpicavet** [comment]
I know some instances of PostgreSQL with peta-byte databases. Would that be enough ?

**Comment by vpicavet** [comment]
Azure / Citus are not the only options, but this article gives you some hint on a PB use case : 

https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/architecting-petabyte-scale-analytics-by-scaling-out-postgres-on/ba-p/969685

> Each Citus cluster currently includes 22 nodes (total of 44 nodes), and together the clusters have a total of 2,816 cores and 18.7 TB of memory. Wei uses 1.5 PB (yes, petabytes) of Azure Premium SSD Managed Disks for the database. And Wei uses another 1.5 PB of Azure blob storage for the staging queue and raw Windows event data.

To get back to your use case, I guess you will see that before needing a distributed PostgreSQL architecture, you have some time ahead. Tables with dozens millions rows in PG are common. Should you go with Billions, it still works. And after that, you have a lot of mechanisms to help improve performances and scale according to your use case.

You may also see that using both relational and non-relational data model in the same app can be a game changer to ease development and improve robustness. This is very easy to do with PG.

**Comment by wodka** [comment]
mhmm - thinking by now of dropping mongodb and going with postgres. For massive scale there are also solutions like cockroachdb.

Before doing this we would need to release at least one version to be able to export the data. (fixing https://github.com/ohmyform/ohmyform/issues/124)

any objections?

**Comment by wodka** [comment]
Release 1 will be with postgres / sqlite support.
