### ISSUE TITLE
Docker fails building ohmyform, missing package.json

### ISSUE THREAD

**Issue by glor** [ohmyform/ohmyform#90]
#### What's this issue about?
Docker shows an interesting error while building the containers

#### Expected behavior
https://ohmyform.com/docs/install/

#### Actual behavior
When running step Four of the *Quick Start* Guide `sudo docker-compose up -d`, I get:
```
Building ohmyform
Step 1/15 : FROM node:12 as builder
 ---> e163934eebb0
Step 2/15 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 2d2bf5b77071
Step 3/15 : COPY ui/ .
 ---> Using cache
 ---> f5ee279f1b42
Step 4/15 : RUN yarn install --frozen-lockfile
 ---> Using cache
 ---> e444d48b09b7
Step 5/15 : RUN yarn export
 ---> Running in 92a4663312d9
yarn run v1.22.4
error Couldn't find a package.json file in "/usr/src/app"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'ohmyform' failed to build: The command '/bin/sh -c yarn export' returned a non-zero code: 1
```

#### Environment
- Manjaro Linux (similar to arch)
- running docker and docker-compose as root (yeah I know, but it shouldn't be an issue here)

**Comment by glor** [comment]
Running in the background, looks good so far. Could that be added to the quick start page?

**Comment by Hedronmx** [comment]
I am having the same issue and I did ran git submodule update --init
