### ISSUE TITLE
Forms are lost after down/up

### ISSUE THREAD

**Issue by nerrixDE** [ohmyform/ohmyform#92]
#### What's this issue about?
Forms are not stored persistent - data is lost after `docker-compose down; docker-compose up -d`
#### Expected behavior
Data is actually stored in a docker volume so it survives restarts
#### Actual behavior
Data is lost after docker container restart
#### Steps to reproduce
1) `git clone https://github.com/ohmyform/ohmyform.git`
2) `cd ohmyform; git submodule update --init; docker-compose up -d`
3) Login on `localhost:5000`, Create a form
4) `docker-compose down; docker-compose up -d`
5) Open `localhost:5000`, all forms are gone.
#### Environment
- Commit [`f5e31b78aaaea272e5f6641b24643e8bec38bcd8`](https://github.com/ohmyform/ohmyform/commit/f5e31b78aaaea272e5f6641b24643e8bec38bcd8)
- Ubuntu 18.04.4 LTS
- Docker 19.03.11
- Docker-Compose 1.25.4

**Edit**:
My `docker-compose.yml` contains:
```
[...]
mongo:
   image: mongo
   volumes:
     - "/srv/docker-persist/ohmymongo:/data"
[...]
```

**Comment by wodka** [comment]
mhmm, there is already the volume defined https://github.com/ohmyform/ohmyform/blob/master/docker-compose.yml - so this should persist the mongodb data

is the folder populated with mongodb data?

**Comment by nerrixDE** [comment]
> mhmm, there is already the volume defined https://github.com/ohmyform/ohmyform/blob/master/docker-compose.yml - so this should persist the mongodb data
> 
> is the folder populated with mongodb data?

In both cases/folders, there is no mongodb data stored.

**Comment by wodka** [comment]
:/ fun thing - the data path changed.


`"./data/mongo:/data/db"` would be the correct mounting path.

as of now there are also examples: https://github.com/ohmyform/ohmyform/blob/master/examples/
