### ISSUE TITLE
Dropdown: Options not saved

### ISSUE THREAD

**Issue by nerrixDE** [ohmyform/ohmyform#93]
###  What's this issue about?
Dropdown Options are not stored

#### Expected behavior
When designing a form, I can add options to select in dropdown-field

#### Actual behavior
I can add option in dropdown-field, however when I hit "save" and reload the page, the entered options are gone.

#### Steps to reproduce
1. Create a form
2. Add dropdown field
3. Add options to select
4. Save Form
5. Reload Page
6. See that all previously created dropdown-options are gone.
#### Environment
- Commit [`a9fbe35faeb058597deb75cdf116cdd03d15b744`](https://github.com/ohmyform/ohmyform/commit/a9fbe35faeb058597deb75cdf116cdd03d15b744)
- Ubuntu 18.04.4 LTS
- Docker 19.03.11
- Docker-Compose 1.25.4

**Comment by wodka** [comment]
ah - could it be that you assign 2 fields the same value?

**Comment by nerrixDE** [comment]
> ah - could it be that you assign 2 fields the same value?

no, I added 3 fields and all 6 fields had different values

**Comment by wodka** [comment]
could you provide values that cause the issue? Try to create a new form to cause the problem

**Comment by nerrixDE** [comment]
> could you provide values that cause the issue? Try to create a new form to cause the problem

Name: "Abc", value: "one"
Name: "Def", value: "two"
Name: "Xyz", value: "three"

**Comment by wodka** [comment]
found the bug and fixed it - will release it soon
