### ISSUE TITLE
Feature Request: Option to disable signups

### ISSUE THREAD

**Issue by nerrixDE** [ohmyform/ohmyform#94]
### Option to disable signups / registration.
I would like to have my own OhMyForm-Instance where not everyone can register and mess with my hosting ressources, upload stuff I could be hold liable for, and so on.

**TL;DR**: Add an option to disable registrations / signups.

**Comment by Leopere** [comment]
This is definitely a good idea to have.

**Comment by wodka** [comment]
next release will use the existing env variable `SIGNUP_DISABLED` (https://github.com/ohmyform/ui/commit/35f7a7d2713ebaf30e1aac381f970eb10d992971)
