### ISSUE TITLE
Issue with dropdown form fields

### ISSUE THREAD

**Issue by jacobwilder** [ohmyform/ohmyform#96]
#### What's this issue about?
When creating a form and adding dropdown options to a question, all options begin with `OK`.
For example, 

#### Expected behavior
Dropdown options exactly as they are set up.

#### Actual behavior
Dropdown options are prefixed with `OK`. For example the choice "Hire a developer" prints to the form as "OKHire a developer"

#### Steps to reproduce
Create a form and add dropdown field with multiple options. Test the form to reproduce.

#### Environment
Win 10 Version 2004
Docker 3.4
Node 12.14

**Comment by wodka** [comment]
thanks, fix now in master and will be in the next release
