### ISSUE TITLE
Container runs as root

### ISSUE THREAD

**Issue by jmhbnz** [ohmyform/ohmyform#97]
### What's this issue about? 
I'm unable to deploy the ohmyform container in my organisation as we have a policy that prevents containers running as root.

#### Expected behavior
Container runs as a non root user.

#### Actual behavior
All app files within the container are owned by root so when attempting to deploy the container on our OpenShift cluster the root user is unable to be used so an unpriviledged user is used instead.

The unpriviledged user is unable to access the app files leading to a permissions error in the pod logs and the ohmyform container failing to start.

#### Steps to reproduce
Below are the steps I take, but spinning up any variation of the current docker image in any platform it can be verified that the container is running as root.
- Docker pull ohmyform:ohmyform image from docker hub.
- Docker push ohmyform image to organisation container registry.
- Create deployment on cluster with ohmyform image
- Review pod logs to see permission error when app attempts to read files within container.

It looks like this is something that was addressed historically, refer #43. I'm new to this project so if someone can give me some gentle guidance I'm happy to give this change a try.

Thanks! 👍

**Comment by Leopere** [comment]
That's an excellent policy we should also not be running this main process as root and now that we are at a stable full rewrite of the application we should be growing up with our Docker practices as well.

**Comment by Leopere** [comment]
https://github.com/ahmedkrmn/ohmyform/blob/9fb70fc3c3102692c6658daca381398ccd01015f/Dockerfile#L5
and 
https://github.com/ahmedkrmn/ohmyform/blob/9fb70fc3c3102692c6658daca381398ccd01015f/Dockerfile#L55

Finally, we should be doing something like this in our separate containers as well.

**Comment by wodka** [comment]
This is a good idea - and I accidentally removed it. It should just be reapplied as in #43 

would you create a PR?

**Comment by jmhbnz** [comment]
Thanks for coming back so quickly, I've attemped a PR here: #98 

I was unsure about the motivations of using `node:12` versus `node:12-alpine` so let me know if that is an issue?  The alpine image appears to be significantly smaller while not impacting ability to buld and run.

**Comment by Leopere** [comment]
Adding -alpine so far causes problems at run time and not at build time.  Me and @wodka are working on a baseline starting at the following.

```DOCKERFILE
## Build API
FROM node:12 as api

WORKDIR /usr/src/app

COPY ui/ .

RUN yarn install --frozen-lockfile
RUN yarn export

## Build APP
FROM node:12 as app
LABEL maintainer="OhMyForm <admin@ohmyform.com>"

WORKDIR /usr/src/app

COPY api/ .
COPY --from=api /usr/src/app/out /usr/src/app/public

RUN yarn install --frozen-lockfile
RUN yarn build

## Production Image.
FROM node:12

WORKDIR /usr/src/app
COPY --from=app /usr/src/app /usr/src/app
RUN addgroup --gid 9999 ohmyform && adduser --disabled-login --uid 9999 --gid 9999 ohmyform
ENV PORT=3000 \
    SECRET_KEY=ChangeMe \
    CREATE_ADMIN=FALSE \
    ADMIN_EMAIL=admin@ohmyform.com \
    ADMIN_USERNAME=root \
    ADMIN_PASSWORD=root

EXPOSE 3000
USER ohmyform
CMD [ "yarn", "start:prod" ]
```

**Comment by wodka** [comment]
Thanks for the changes!

**Comment by nhutran1201** [comment]
#43
