### ISSUE TITLE
Move to NodeJS 14

### ISSUE THREAD

**Issue by wodka** [ohmyform/ohmyform#99]
#### What's this issue about?

currently we use NodeJS 12, we should move to the next LTS version

https://nodejs.org/en/about/releases/

![image](https://user-images.githubusercontent.com/385731/84745113-66175280-afb4-11ea-8e70-c19cadf11295.png)

**Comment by Leopere** [comment]
Looks like the deadline on this is technically far into 2021+ however we might benefit from being in the latest LTS we should weigh the pros and cons out in the coming months.  Perhaps if we start seeing far too many vulnerability reports that we need to close between now and then we will be nudged to move forward sooner than later.

**Comment by wodka** [comment]
I think we should stick to the LTS Version - in October node 12 will be surpassed by node 14. Then I would switch our containers

**Comment by Leopere** [comment]
Just a scheduled bump of this thread so we’re on top of it.

**Comment by wodka** [comment]
We need to update the docker files and test if everything still works / builds, should be fairly easy

**Comment by kmjayadeep** [comment]
Hi, I would like to take this up

**Comment by Leopere** [comment]
Can we make sure to mark these PR’s property with the Hacktoberfest labels?

**Comment by wodka** [comment]
I think all are labeled properly - also added the tags now to the repository

**Comment by kmjayadeep** [comment]
you can add `hacktoberfest` topic to the repo and then it is not required to label individual PRs anymore

**Comment by Leopere** [comment]
done
